### ISSUE TITLE
Can't access Library

### ISSUE THREAD

**Issue by kilmerc** [openaudible/openaudible#1006]
Even after the previous fix that was released, I cannot get past the cannot load library error. Nothing has changed with or seems to be wrong with my drive, but at this point, I will accept that a different drive may be needed. My question is, I have a massive library already set up with audible and manually added books on that drive. Is there an easy way to get all that same data on a different location and point openaudible to it instead? Right now I can't even get into open audible at all as I get an exception after I click continue when it hit the error about my library. Any help would be welcome as I cannot use open audible until I can get it resolved. Thanks!

here are the logs for your benefit

Coltons-MacBook-Pro:~ colton$ cd /Applications/OpenAudible.app/Contents/Resources/app
Coltons-MacBook-Pro:app colton$ ./debug_mac.sh
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
Aug 23, 2022 9:07:59 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 3.5.9 for cocoa swt 4950 jvm 11.0.15
Aug 23, 2022 9:08:00 PM org.openaudible.Directories cleanMetaDir
WARNING: No BASE directory found
Aug 23, 2022 9:08:00 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/colton/Library/OpenAudible/settings.json exists=true size=568
Aug 23, 2022 9:08:00 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1605751527304
Aug 23, 2022 9:08:00 PM org.openaudible.desktop.swt.layout.Theme setTheme
INFO: Setting color theme to dark
Aug 23, 2022 9:08:00 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 3.5.9 mac
Aug 23, 2022 9:08:00 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
Aug 23, 2022 9:08:01 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/colton/Library/OpenAudible/settings.json exists=true size=568
Aug 23, 2022 9:08:01 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1605751527304
Aug 23, 2022 9:08:01 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
Aug 23, 2022 9:08:01 PM org.openaudible.Audible load
INFO: Loading /Volumes/Seagate Backup Plus Drive/Open Audible/books.json
Aug 23, 2022 9:08:01 PM org.openaudible.Audible load
SEVERE: Error loading
java.nio.file.FileSystemException: /Volumes/Seagate Backup Plus Drive/Open Audible/books.json: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
	at org.openaudible.util.HTMLUtil.readFile(HTMLUtil.java:27)
	at org.openaudible.books.BookJSON.readBooks(BookJSON.java:134)
	at org.openaudible.Audible.loadBooks(Audible.java:607)
	at org.openaudible.Audible.load(Audible.java:642)
	at org.openaudible.desktop.swt.manager.AudibleGUI.load(AudibleGUI.java:886)
	at org.openaudible.desktop.swt.manager.AudibleGUI$4.run(AudibleGUI.java:962)

Aug 23, 2022 9:08:01 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Loading} [layout=GridLayout {numColumns=2 marginWidth=12 marginHeight=21 horizontalSpacing=14 verticalSpacing=8}] visible=true input shell:Shell {OpenAudible} [layout=GridLayout {horizontalSpacing=5 verticalSpacing=5}]
Exception in thread "Timer-1" java.lang.NullPointerException
	at org.openaudible.bookfiles.BookFiles.readDirectory(BookFiles.java:214)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:149)
	at org.openaudible.bookfiles.BookFiles.updateFileCache(BookFiles.java:130)
	at org.openaudible.bookfiles.BookFiles.checkFileCache(BookFiles.java:260)
	at org.openaudible.bookfiles.BookFiles$1.run(BookFiles.java:77)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Aug 23, 2022 9:08:04 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error loading books body:Error loading books from file:
/Volumes/Seagate Backup Plus Drive/Open Audible/books.json
File may be damaged, or an application error occurred. 
Error:/Volumes/Seagate Backup Plus Drive/Open Audible/books.json: Operation not permitted

An error prevented loading your books. You can Quit or Continue. response:BUTTON_CONTINUE
Aug 23, 2022 9:08:04 PM org.openaudible.Audible checkLibrary
INFO: loaded 0 books.
Aug 23, 2022 9:08:04 PM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Error starting
java.lang.NullPointerException
	at org.openaudible.bookfiles.BookFiles.readDirectory(BookFiles.java:214)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:149)
	at org.openaudible.bookfiles.BookFiles.forceUpdate(BookFiles.java:282)
	at org.openaudible.books.BookNotifier.preflight(BookNotifier.java:123)
	at org.openaudible.books.BookNotifier.booksUpdated(BookNotifier.java:109)
	at org.openaudible.desktop.swt.manager.AudibleGUI.load(AudibleGUI.java:904)
	at org.openaudible.desktop.swt.manager.AudibleGUI$4.run(AudibleGUI.java:962)

Aug 23, 2022 9:08:04 PM org.openaudible.desktop.swt.gui.MessageBoxFactory showError
SEVERE: showError
java.lang.NullPointerException
	at org.openaudible.bookfiles.BookFiles.readDirectory(BookFiles.java:214)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:149)
	at org.openaudible.bookfiles.BookFiles.forceUpdate(BookFiles.java:282)
	at org.openaudible.books.BookNotifier.preflight(BookNotifier.java:123)
	at org.openaudible.books.BookNotifier.booksUpdated(BookNotifier.java:109)
	at org.openaudible.desktop.swt.manager.AudibleGUI.load(AudibleGUI.java:904)
	at org.openaudible.desktop.swt.manager.AudibleGUI$4.run(AudibleGUI.java:962)

Aug 23, 2022 9:08:04 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error
java.lang.NullPointerException
Aug 23, 2022 9:08:04 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Loading} [layout=GridLayout {numColumns=2 marginWidth=12 marginHeight=21 horizontalSpacing=14 verticalSpacing=8}] visible=true input shell:Shell {OpenAudible} [layout=GridLayout {horizontalSpacing=5 verticalSpacing=5}]
Aug 23, 2022 9:08:04 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Loading} [layout=GridLayout {numColumns=2 marginWidth=12 marginHeight=21 horizontalSpacing=14 verticalSpacing=8}] visible=true input shell:Shell {OpenAudible} [layout=GridLayout {horizontalSpacing=5 verticalSpacing=5}]
Aug 23, 2022 9:08:05 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error body:java.lang.NullPointerException response:BUTTON_OK
Aug 23, 2022 9:08:05 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Aug 23, 2022 9:08:05 PM org.openaudible.audible.APIManager postInit
INFO: postInit API ready.
Exception in thread "main" java.lang.NullPointerException
	at org.openaudible.audible.MigrateFileSystem.addDirectory(MigrateFileSystem.java:126)
	at org.openaudible.audible.MigrateFileSystem.getFilesToMove(MigrateFileSystem.java:118)
	at org.openaudible.audible.MigrateFileSystem.migrate_gui(MigrateFileSystem.java:178)
	at org.openaudible.desktop.swt.manager.AudibleGUI.applicationStarted(AudibleGUI.java:995)
	at org.openaudible.desktop.swt.manager.Application.applicationStarted(Application.java:94)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:389)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:128)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:141)
	at org.openaudible.desktop.Application.main(Application.java:48)

**Comment by openaudible** [comment]
This is a security issue with Mac. I believe you need to authorize OpenAudible to be allowed to access your /Volumes/Seagate Backup Plus Drive/Open Audible/ .

https://support.apple.com/guide/mac-help/control-access-to-files-and-folders-on-mac-mchld5a35146/mac

So from Settings: Security & Privacy, then look at Full Disk Access and Files and Folders.

You're supposed to be able to add an application to Files and Folders, but for me (and many others) the plus (add) sign is disabled. It is possible to give OpenAudible "Full Disk access"

You could also check the sharing and permissions on your remote drive. 

There is also one bug you found, which is the NullPointerException.. which I'll fix in a beta. 

Will also look more at the permissions thing... maybe there is something I can do on our end to let Apple know users may want to access any random disk location.

**Comment by openaudible** [comment]
If there are any Mac experts out there that know about allowing apps to access remote volumes... let me know!

**Comment by kilmerc** [comment]
As always, thanks so much for your responsiveness. Granting full disk access to OPENAUDIBLE in settings did the trick. Everything is working as expected now. Thank you so much!
