### ISSUE TITLE
Failure when trying to authenticate

### ISSUE THREAD

**Issue by wolfe719** [openaudible/openaudible#1122]
Reformatted and re-installed MacOS Big Sur 11.7.3 on iMac (Retina 5K, 27-inch, Late 2014)

Download, install and run OpenAudible app (does not matter whether release version 3.6.3, or beta version 3.6.3.10beta)

Select Controls | Connect to Audible

On Release version: See dialog asking for Audible Region (US - audible.com), and Login with Audible User Name (for Legacy users.) - does not matter which option I select

On Beta version: See dialog asking to select Login Method: Secure OpenAudible Login (Recommended) or Secure Web Browser Login (Alternate) - either selection fails as well.

I enter in username/password (username is my email - has been for years since my first Audible book purchase).

The window says it needs to further verify that I am a human being, and offers a Captcha of string entry. 

Enter in the correct string, and my username / password again --> java.lang.NullPointerException

Console shows the following:

```
b 03, 2023 12:44:41 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Feb 03, 2023 12:44:57 PM org.openaudible.audible.api.login.Login loginDefault
INFO: logging on to audible US
Feb 03, 2023 12:44:57 PM org.openaudible.audible.api.login.Login build_oauth_url
INFO: params{
accountStatusPolicy=2b
forceMobileLayout=4b
language=5b
marketPlaceId=13b
openid.assoc_handle=19b
openid.claimed_id=50b
openid.identity=50b
openid.mode=13b
openid.ns=32b
openid.ns.oa2=36b
openid.ns.pape=43b
openid.oa2.client_id=117b
openid.oa2.response_type=5b
openid.oa2.scope=18b
openid.pape.max_auth_age=1b
openid.return_to=36b
pageId=16b
}
Feb 03, 2023 12:44:57 PM org.openaudible.audible.api.login.Login build_oauth_url
INFO: u=https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36313133434536373142434135374439343433313136443533464136323741313337314545333244234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:44:57 PM org.openaudible.audible.api.login.Login request
INFO: login request:get https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A36313133434536373142434135374439343433313136443533464136323741313337314545333244234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0 null
Feb 03, 2023 12:44:57 PM org.openaudible.util.BugReport sendBetaMetric
INFO: Bug report received: {"success": true}
Feb 03, 2023 12:44:57 PM org.openaudible.desktop.swt.manager.login.LoginGUI login
SEVERE: Unable to login!
java.lang.NullPointerException
	at org.openaudible.audible.api.login.Login.request(Login.java:667)
	at org.openaudible.audible.api.login.Login.getDocument(Login.java:108)
	at org.openaudible.audible.api.login.Login.loginDefault(Login.java:797)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.loginWithoutBrowser(LoginGUI.java:38)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.login(LoginGUI.java:22)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.login(LoginGUI.java:92)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.connectToAudibleAPI(LoginGUI.java:85)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:363)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:72)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:542)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:291)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:391)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:135)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:148)
	at org.openaudible.desktop.Application.main(Application.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

Feb 03, 2023 12:44:57 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Login Error
A problem was encountered logging in.
Consider reporting this bug...

Feb 03, 2023 12:44:57 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {OpenAudible} [layout=GridLayout {horizontalSpacing=5 verticalSpacing=5}] visible=true input shell:null
Feb 03, 2023 12:44:57 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {OpenAudible} [layout=GridLayout {horizontalSpacing=5 verticalSpacing=5}] visible=true input shell:null
Feb 03, 2023 12:45:00 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Login Error body:A problem was encountered logging in.
Consider reporting this bug...

java.lang.NullPointerException response:BUTTON_OK
Feb 03, 2023 12:46:50 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.login.LoginGUI loginInternal
INFO: logging on to audible US
Feb 03, 2023 12:47:01 PM org.openaudible.audible.api.login.Login build_oauth_url
INFO: params{
accountStatusPolicy=2b
forceMobileLayout=4b
language=5b
marketPlaceId=13b
openid.assoc_handle=19b
openid.claimed_id=50b
openid.identity=50b
openid.mode=13b
openid.ns=32b
openid.ns.oa2=36b
openid.ns.pape=43b
openid.oa2.client_id=117b
openid.oa2.response_type=5b
openid.oa2.scope=18b
openid.pape.max_auth_age=1b
openid.return_to=36b
pageId=16b
}
Feb 03, 2023 12:47:01 PM org.openaudible.audible.api.login.Login build_oauth_url
INFO: u=https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A45334230433434323938464331433134394146424634433839393646423932343237414534314534234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.login.LoginGUI loginInternal
INFO: Login URL for external browser is: 
https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A45334230433434323938464331433134394146424634433839393646423932343237414534314534234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:47:01 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/wolfe/Library/OpenAudible/settings.json exists=true size=663
Feb 03, 2023 12:47:01 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1675444543334
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.browser.swt.AudibleBrowser createBrowser
INFO: creating browser of type: default
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.browser.swt.AudibleBrowser createBrowser
INFO: created browser of type: webkit
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.login.LoginInternal browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A45334230433434323938464331433134394146424634433839393646423932343237414534314534234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.login.LoginInternal browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A45334230433434323938464331433134394146424634433839393646423932343237414534314534234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.login.LoginInternal browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A45334230433434323938464331433134394146424634433839393646423932343237414534314534234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.login.LoginInternal browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A45334230433434323938464331433134394146424634433839393646423932343237414534314534234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:47:01 PM org.openaudible.desktop.swt.manager.login.LoginInternal browserEvent
INFO: browserEvent: changed https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A45334230433434323938464331433134394146424634433839393646423932343237414534314534234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:47:17 PM org.openaudible.desktop.swt.manager.login.LoginInternal browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin
Feb 03, 2023 12:47:17 PM org.openaudible.desktop.swt.manager.login.LoginInternal browserEvent
INFO: browserEvent: changing https://www.amazon.com/ap/signin
Feb 03, 2023 12:47:17 PM org.openaudible.desktop.swt.manager.login.LoginInternal browserEvent
INFO: browserEvent: changed https://www.amazon.com/ap/signin
Feb 03, 2023 12:50:22 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Feb 03, 2023 12:51:29 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Feb 03, 2023 12:53:55 PM org.openaudible.audible.api.login.Login loginDefault
INFO: logging on to audible US
Feb 03, 2023 12:53:55 PM org.openaudible.audible.api.login.Login build_oauth_url
INFO: params{
accountStatusPolicy=2b
forceMobileLayout=4b
language=5b
marketPlaceId=13b
openid.assoc_handle=19b
openid.claimed_id=50b
openid.identity=50b
openid.mode=13b
openid.ns=32b
openid.ns.oa2=36b
openid.ns.pape=43b
openid.oa2.client_id=117b
openid.oa2.response_type=5b
openid.oa2.scope=18b
openid.pape.max_auth_age=1b
openid.return_to=36b
pageId=16b
}
Feb 03, 2023 12:53:55 PM org.openaudible.audible.api.login.Login build_oauth_url
INFO: u=https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A41313341424531444439443142333131344632433535394631443244424230353543454641304236234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Feb 03, 2023 12:53:55 PM org.openaudible.audible.api.login.Login request
INFO: login request:get https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&forceMobileLayout=true&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&accountStatusPolicy=P1&marketPlaceId=AF2M0KC94RCEA&language=en-US&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fmaplanding&openid.oa2.response_type=token&openid.assoc_handle=amzn_audible_ios_us&openid.mode=checkid_setup&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.oa2.client_id=device%3A41313341424531444439443142333131344632433535394631443244424230353543454641304236234132435a4a5a474c4b324a4a564d&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0 null
Feb 03, 2023 12:53:55 PM org.openaudible.util.BugReport sendBetaMetric
INFO: Bug report received: {"success": true}
Feb 03, 2023 12:53:55 PM org.openaudible.desktop.swt.manager.login.LoginGUI login
SEVERE: Unable to login!
java.lang.NullPointerException
	at org.openaudible.audible.api.login.Login.request(Login.java:667)
	at org.openaudible.audible.api.login.Login.getDocument(Login.java:108)
	at org.openaudible.audible.api.login.Login.loginDefault(Login.java:797)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.loginWithoutBrowser(LoginGUI.java:38)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.login(LoginGUI.java:22)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.login(LoginGUI.java:92)
	at org.openaudible.desktop.swt.manager.login.LoginGUI.connectToAudibleAPI(LoginGUI.java:85)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:363)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:72)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:542)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:291)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:391)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:135)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:148)
	at org.openaudible.desktop.Application.main(Application.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

Feb 03, 2023 12:53:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Login Error
A problem was encountered logging in.
Consider reporting this bug...

Feb 03, 2023 12:53:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {OpenAudible} [layout=GridLayout {horizontalSpacing=5 verticalSpacing=5}] visible=true input shell:null
Feb 03, 2023 12:53:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {OpenAudible} [layout=GridLayout {horizontalSpacing=5 verticalSpacing=5}] visible=true input shell:null
Feb 03, 2023 12:54:20 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Login Error body:A problem was encountered logging in.
Consider reporting this bug...

java.lang.NullPointerException response:BUTTON_OK
Feb 03, 2023 12:54:22 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: sw_vers 
Feb 03, 2023 12:54:22 PM org.openaudible.util.BugReport sendReport
INFO: Sending bug report: {
 "date": "Fri Feb 03 12:54:22 EST 2023",
 "uid": "1675444543334",
 "memory": "Memory: Using 70.863Mb of 8192Mb (1%) Min 29.865Mb Max 70.863Mb",
 "what": "Description of problem",
 "issue": 1098,
 "region": "US",
 "version": "3.6.3.10",
 "platform": "mac",
 "beta": {
  "connected": false,
  "errors": false
 },
 "email": ""
}
Length:11515 to https://openaudible.org/api/send_bugreport?version=3.6.3.10&platform=mac&mode=beta
Feb 03, 2023 12:54:22 PM org.openaudible.util.BugReport sendReport
INFO: Bug report received: {
 "msg": "Thank you for your report! I hope we can help.",
 "success": true
}
Feb 03, 2023 12:54:24 PM org.openaudible.desktop.swt.manager.dialogs.BugReportDialog okPressed
INFO: sent bug report
Feb 03, 2023 12:54:31 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
```

**Comment by openaudible** [comment]
Thank you for that report. Try the latest beta 11. Should fix that.

**Comment by openaudible** [comment]
Try upgrading the beta. Should be fixed.
