### ISSUE TITLE
Downloading does not work

### ISSUE THREAD

**Issue by scheffe2804** [openaudible/openaudible#1179]
Hi there,

the Program stops downloading the Audible books.
Log :
März 31, 2023 3:07:42 PM org.openaudible.Audible jobCompleted
INFORMATION: DownloadQueue completed:Game of Thrones - Das Lied von E DownloadQueue size:1 remain:0 success:0 fail:161 threads:2
März 31, 2023 3:07:42 PM org.openaudible.audible.api.Client requestBytes
WARNUNG: https://api.audible.de/1.0/content/B004UZRCVQ/licenserequest -> HttpResponseProxy{HTTP/1.1 400 Bad Request [Content-Type: application/json, Content-Length: 152, Connection: keep-alive, Server: Server, Date: Fri, 31 Mar 2023 13:07:40 GMT, x-amz-rid: VC2R4FE9CY8PS4R791C4, x-amzn-RequestId: e079fc12-7acd-4387-a782-18ee8bb21084, X-Amz-Date: Fri, 31 Mar 2023 13:07:40 GMT, x-amzn-ErrorType: ValidationException:http://internal.amazon.com/coral/com.amazon.coral.validate/, nnCoection: close, Vary: Content-Type,Accept-Encoding,User-Agent, Strict-Transport-Security: max-age=47474747; includeSubDomains; preload, X-Cache: Error from cloudfront, Via: 1.1 2a449514cebabcf6ab64b86d6a229cfe.cloudfront.net (CloudFront), X-Amz-Cf-Pop: TXL50-P2, X-Amz-Cf-Id: wV8X0cGyraw4DIhKoGjPpsPen7BM1fzEYqIRVvkmXn3PwdlbKTwrVQ==] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 152,Chunked: false]}}
März 31, 2023 3:07:42 PM org.openaudible.util.queues.ThreadedQueue jobError
INFORMATION: DownloadQueue error processing Download Game of Thrones - Das Lied von E item Game of Thrones - Das Lied von E
java.io.IOException: http error getting: https://api.audible.de/1.0/content/B004UZRCVQ/licenserequest reason:Bad Request
	at org.openaudible.audible.api.Client.requestBytes(Client.java:151)
	at org.openaudible.audible.api.Client.request(Client.java:82)
	at org.openaudible.audible.api.Client.post(Client.java:76)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:566)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:557)
	at org.openaudible.audible.APIManager.getAAXCDownloadLink(APIManager.java:96)
	at org.openaudible.download.DownloadAAXJob.preProcessAAXC(DownloadAAXJob.java:237)
	at org.openaudible.download.DownloadAAXJob.downloadAlt(DownloadAAXJob.java:197)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:207)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:516)
	
	
	Regards Chris

**Comment by openaudible** [comment]
Check out this and let me know what you've tried:
https://openaudible.org/docs#download_errors
