### ISSUE TITLE
Unable to download the book from library

### ISSUE THREAD

**Issue by DummyGNP** [openaudible/openaudible#1241]
License applied to OpenAudible. I have tried restarting, signing out from Audible and then logging back in but the issue persists. Here is the error from the Logs:

```
INFO: DownloadQueue completed:A Light on the Hill DownloadQueue size:0 remain:0 success:0 fail:4 threads:1 jobs:0
srp 07, 2023 6:32:38 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Download
srp 07, 2023 6:32:38 PM org.openaudible.desktop.swt.manager.AudibleGUI downloadAAX
INFO: Added 1 of 1
srp 07, 2023 6:32:38 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job Download The Love Letter DownloadQueue size:1 remain:0 success:0 fail:4 threads:1 jobs:0
srp 07, 2023 6:32:38 PM org.openaudible.util.queues.ThreadedQueue jobStarted
INFO: DownloadQueue started:The Love Letter DownloadQueue size:1 remain:0 success:0 fail:4 threads:1 jobs:1
srp 07, 2023 6:32:38 PM org.openaudible.download.DownloadJob _download
INFO: Download failed:C:\Users\User\OpenAudible\tmp\The Love Letter.AAX_-1480138683.part The Love Letter progress: null unable to resume, fileLen=0 bytes.
srp 07, 2023 6:32:38 PM org.openaudible.download.DownloadJob download
WARNING: Error downloading, will try again: The Love Letter.AAX attempt 1
HTTP/1.1 204 No Content
	at org.openaudible.download.DownloadJob.checkResponse(DownloadJob.java:313)
	at org.openaudible.download.DownloadJob._download(DownloadJob.java:198)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:124)
	at org.openaudible.download.DownloadAAXJob.downloadAlt(DownloadAAXJob.java:222)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:230)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:567)
```

**Comment by DummyGNP** [comment]
I am on the latest version 3.8.1
