### ISSUE TITLE
OA 3.9.1 Does not seem to be actually converting the AAX to M4B

### ISSUE THREAD

**Issue by WHGH2** [openaudible/openaudible#1277]
OA 3.9.1 Does not seem to be actually converting the AAX to M4B. State shows "Converting..." but otherwise no action occurs. Earlier version worked when tried a few months back. Did the log out, log back in, full sync, and redownload, but same result.

**Comment by Antiros1** [comment]
Hello, also seeing the same thing. The console shows the following:

**### For M4B:** 

Oct 02, 2023 9:07:31 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert
Oct 02, 2023 9:07:31 PM org.openaudible.util.queues.ThreadedQueue run
SEVERE: jobThread error!
java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "this.outputFile" is null
	at org.openaudible.convert.ConvertJob.<init>(ConvertJob.java:112)
	at org.openaudible.convert.ConvertJob.<init>(ConvertJob.java:77)
	at org.openaudible.convert.ConvertQueue.createJob(ConvertQueue.java:37)
	at org.openaudible.convert.ConvertQueue.createJob(ConvertQueue.java:17)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:555)


**### For MP3:**

Oct 02, 2023 9:09:03 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert_MP3
Oct 02, 2023 9:09:03 PM org.openaudible.util.queues.ThreadedQueue run
SEVERE: jobThread error!
java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "this.outputFile" is null
	at org.openaudible.convert.ConvertJob.<init>(ConvertJob.java:112)
	at org.openaudible.convert.ConvertJob.<init>(ConvertJob.java:77)
	at org.openaudible.convert.ConvertQueue.createJob(ConvertQueue.java:37)
	at org.openaudible.convert.ConvertQueue.createJob(ConvertQueue.java:17)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:555)

**Comment by openaudible** [comment]
Confirmed. Replacing with 3.9.2. Will be there shortly.

**Comment by openaudible** [comment]
Sorry for the bug on our end. Replaced with 3.9.2. Thank you!
