### ISSUE TITLE
3.9.2 on Mac M1 - Sonoma 14.1. - Still cannot find new purchase and several other issues

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1279]
1. First run came up with need to remove some Amazon virtual connections - which I did
2. second attempt to run said I had about 1528 books to download!!  Which I do not intend to do, it will take a couple of days
3. I logout from the audible connection and restart the app for a last attempt .... I am not logged in but it now says 1028 books to download, so I log into audible
4. It now asks do I want to start a full sync, just for the hell of it I say yes...
5. It comes up agin with the error registering virtual device - again

Log attached - can you fix this mess - the last series of updates and releases has been a joke - what is happening?

org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1209)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:708)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1372)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.getDefaultShell(ProgressDialog.java:67)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.doProgressTask(ProgressDialog.java:81)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshLibrary(AudibleGUI.java:355)
	at org.openaudible.audible.APIManager.registerDevice(APIManager.java:245)
	at org.openaudible.audible.APIManager.takeLogin(APIManager.java:153)
	at org.openaudible.desktop.swt.manager.login.LoginInternalBrowser.handleMapLanding(LoginInternalBrowser.java:127)
	at org.openaudible.desktop.swt.manager.login.LoginInternalBrowser.lambda$takeURL$0(LoginInternalBrowser.java:170)
	at java.base/java.lang.Thread.run(Thread.java:833)

:org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1209)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:708)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1372)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.getDefaultShell(ProgressDialog.java:67)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.doProgressTask(ProgressDialog.java:81)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshLibrary(AudibleGUI.java:355)
	at org.openaudible.audible.APIManager.registerDevice(APIManager.java:245)
	at org.openaudible.audible.APIManager.takeLogin(APIManager.java:153)
	at org.openaudible.desktop.swt.manager.login.LoginInternalBrowser.handleMapLanding(LoginInternalBrowser.java:127)
	at org.openaudible.desktop.swt.manager.login.LoginInternalBrowser.lambda$takeURL$0(LoginInternalBrowser.java:170)
	at java.base/java.lang.Thread.run(Thread.java:833)

Oct 03, 2023 9:18:07 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error registering virtual device
Error creating a virtual device to communicate with Audible. You may need to delete some of your registered audible devices. Visit https://help.audible.com/s/article/how-can-i-deactivate-devices-that-are-using-the-audible-app
Check the Console for more details.
3.9.2
Oct 03, 2023 9:18:07 AM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {OpenAudible} [layout=GridLayout {}] visible=true input shell:null
Oct 03, 2023 9:18:07 AM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {OpenAudible} [layout=GridLayout {}] visible=true input shell:null
Oct 03, 2023 9:18:35 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error registering virtual device body:Error creating a virtual device to communicate with Audible. You may need to delete some of your registered audible devices. Visit https://help.audible.com/s/article/how-can-i-deactivate-devices-that-are-using-the-audible-app
Check the Console for more details. response:BUTTON_OK
Oct 03, 2023 9:19:56 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
Good report. Will fix.

**Comment by openaudible** [comment]
Fixed in 3.9.3. 
Thank you for the report.
