### ISSUE TITLE
failed to do a quick sync and it fails ver 4.0.5 - Request could not be authenticated

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1350]
Feb 22, 2024 9:17:32 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 4.0.5 for win32 swt 4963 jvm 18.0.1
Feb 22, 2024 9:17:33 PM org.openaudible.Directories load
INFO: Loading directories. These must be online and read/writable:
->{
 "ZIP": "",
 "META": "C:\\Users\\Lee Mackinnell\\OpenAudible",
 "APP": "C:\\Program Files\\OpenAudible",
 "ART": "",
 "BOOKS": "",
 "BASE": "P:\\Plex Extra\\OpenAudibleFiles",
 "MP3": "",
 "PDF": "",
 "WEB": "P:\\Plex Extra\\OpenAudibleFiles",
 "TMP": "C:\\Users\\Lee Mackinnell\\OpenAudible\\tmp",
 "AAX": "",
 "M4B": "",
 "M4A": ""
}
Feb 22, 2024 9:17:33 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\Lee Mackinnell\OpenAudible\settings.json exists=true size=625
Feb 22, 2024 9:17:33 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595779281984 format=M4B
Feb 22, 2024 9:17:33 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\Lee Mackinnell\OpenAudible\settings.json exists=true size=625
Feb 22, 2024 9:17:33 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595779281984 format=M4B
Feb 22, 2024 9:17:34 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\Lee Mackinnell\OpenAudible\settings.json exists=true size=625
Feb 22, 2024 9:17:34 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595779281984 format=M4B
Feb 22, 2024 9:17:34 PM org.openaudible.desktop.swt.layout.Theme setTheme
INFO: Setting color theme to dark
Feb 22, 2024 9:17:34 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 4.0.5 win
Feb 22, 2024 9:17:34 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
Feb 22, 2024 9:17:36 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\Lee Mackinnell\OpenAudible\settings.json exists=true size=625
Feb 22, 2024 9:17:36 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595779281984 format=M4B
Feb 22, 2024 9:17:36 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Feb 22, 2024 9:17:39 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 1. Refreshed file cache:4652 files. [] took 2436 ms. to complete.
Feb 22, 2024 9:17:39 PM org.openaudible.library.BookLibrary load
INFO: Loading P:\Plex Extra\OpenAudibleFiles\books.json length 7363379
Feb 22, 2024 9:17:39 PM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Feb 22, 2024 9:17:42 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 2. Refreshed file cache:4652 files. [] took 1239 ms. to complete.
Feb 22, 2024 9:17:43 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 7.068 seconds to complete.
Feb 22, 2024 9:17:46 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Feb 22, 2024 9:17:53 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Quick_Refresh
Feb 22, 2024 9:17:53 PM org.openaudible.audible.LibraryScanner library
INFO: getting library from API since Mon Feb 19 00:00:00 AEST 2024
Feb 22, 2024 9:17:55 PM org.openaudible.audible.api.Client requestBytes
WARNING: error getting: https://api.audible.com/1.0/library?response_groups=product_attrs%2C+contributors%2C+customer_rights%2C+relationships%2C+media%2C+product_desc%2C+product_extended_attrs%2C+pdf_url%2C+series%2C+category_ladders%2C+rating%2C+sku%2C+listening_status%2C+percent_complete%2C+is_finished&num_results=100&page=1&sort_by=PurchaseDate&purchased_after=2024-02-19T00%3A00%3A00%2B10%3A00 -> Forbidden {"message":"Request could not be authenticated"}
Feb 22, 2024 9:17:55 PM org.openaudible.audible.LibraryScanner library
INFO: Successfully got 0 book(s) from library with since Mon Feb 19 00:00:00 AEST 2024
Feb 22, 2024 9:17:55 PM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Unable to get library
java.io.IOException: http error getting: https://api.audible.com/1.0/library?response_groups=product_attrs%2C+contributors%2C+customer_rights%2C+relationships%2C+media%2C+product_desc%2C+product_extended_attrs%2C+pdf_url%2C+series%2C+category_ladders%2C+rating%2C+sku%2C+listening_status%2C+percent_complete%2C+is_finished&num_results=100&page=1&sort_by=PurchaseDate&purchased_after=2024-02-19T00%3A00%3A00%2B10%3A00 reason:Forbidden error {"message":"Request could not be authenticated"}
	at org.openaudible.audible.api.Client.requestBytes(Client.java:179)
	at org.openaudible.audible.api.Client.request(Client.java:97)
	at org.openaudible.audible.api.Client.get(Client.java:255)
	at org.openaudible.audible.api.API.getBooks(API.java:110)
	at org.openaudible.audible.api.API.getBooks(API.java:93)
	at org.openaudible.audible.LibraryScanner._getLibraryBooks(LibraryScanner.java:219)
	at org.openaudible.audible.LibraryScanner.library(LibraryScanner.java:366)
	at org.openaudible.audible.LibraryScanner.library(LibraryScanner.java:123)
	at org.openaudible.audible.APIManager.library(APIManager.java:171)
	at org.openaudible.audible.APIManager.library(APIManager.java:165)
	at org.openaudible.desktop.swt.manager.AudibleGUI$1.run(AudibleGUI.java:323)

Feb 22, 2024 9:17:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error refreshing library
Unexpected error refreshing your library. Check the log.
If this persists, you may need to Log out of Audible and Log into Audible from the Controls Menu.
There is also a troubleshooting guide in the documentation.
4.0.5
Feb 22, 2024 9:17:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Lee's 2nd Audible for iPhone} [layout=GridLayout {numColumns=2 marginWidth=11 marginHeight=13 horizontalSpacing=12 verticalSpacing=8}] visible=true input shell:null
Feb 22, 2024 9:17:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Lee's 2nd Audible for iPhone} [layout=GridLayout {numColumns=2 marginWidth=11 marginHeight=13 horizontalSpacing=12 verticalSpacing=8}] visible=true input shell:null
Feb 22, 2024 9:17:59 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error refreshing library body:Unexpected error refreshing your library. Check the log.
If this persists, you may need to Log out of Audible and Log into Audible from the Controls Menu.
There is also a troubleshooting guide in the documentation. response:BUTTON_OK
Feb 22, 2024 9:17:59 PM org.openaudible.desktop.swt.manager.AudibleGUI downloadAndConvertWithDialog
INFO: You have 76 books to download
You have 6 books to convert to M4B

 autoConvert=false
Feb 22, 2024 9:18:03 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:START_JOBS_TITLE body:You have 76 books to download
You have 6 books to convert to M4B

Would you like to start these tasks now? response:BUTTON_NO

**Comment by openaudible** [comment]
Go to your Manage Accounts. Run the Test All. Remove and duplicates or Errors. Then try again.
Posted a new beta as well for handing duplicate accounts better.
https://openaudible.org/beta

**Comment by feldegast** [comment]
while i would like to use duplicate accounts (same account on different servers) that report was with just a single account connected to the US server
i will send a long error log shortly

**Comment by openaudible** [comment]
For our purposes, duplicate accounts are two accounts from the same region with same credentials -- but have different device identification. So those are "bad". But if you have two accounts in different regions with same name or email it may be hard to distinguish them. I can add a "region" too the account manager to help distinguish them.

**Comment by feldegast** [comment]
that would be great, i can see both situations happening, books bought from
audible.in are a lot cheaper than from AU and US servers, that's why i
bought from that region.

**Comment by feldegast** [comment]
sent an email with a bug report for 4.0.5.2beta

**Comment by feldegast** [comment]
sent a bug report for 4.0.5 beta 5 after pressing test all on account manager
![image](https://github.com/openaudible/openaudible/assets/1029921/89be67d2-cec8-4364-b71a-6b6785225bdb)
here is the relevent screen shot

**Comment by openaudible** [comment]
Got it. Fixing it. Thank you.

**Comment by feldegast** [comment]
getting beta6 to test

**Comment by feldegast** [comment]
after clicking test all, the white text in the frame rurns black making it unreadable in dark mode
![image](https://github.com/openaudible/openaudible/assets/1029921/bc3dc263-d5ad-415f-ae0d-186b7f910e92)

**Comment by feldegast** [comment]
testing beta7
