### ISSUE TITLE
Downloading book and server says missing product atributes

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1369]
Downloading a specific book, i bought it from the Australian server
I am connected to US, UK and AU servers and it shows in that order in the Account Manager
it tries to download the book from the UK server and fails
how can i say "try the AU server to download"?
or have OpenAudible try a different server in the event of an error automatically?
or have a prefered order for the app to try each server?
if i disable the UK server in the account manager it still tries to download the book from the UK server
the same thing happens when i disable all servers except the AU server, it still tries to get the book from the UK server

Mar 06, 2024 11:59:10 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 4.1.1 for win64 swt 4963 jvm 18.0.1
Mar 06, 2024 11:59:11 PM org.openaudible.Directories load
INFO: Library path set to P:\Plex Extra\OpenAudibleFiles\books
Mar 06, 2024 11:59:11 PM org.openaudible.desktop.swt.layout.Theme setTheme
INFO: Setting color theme to dark
Mar 06, 2024 11:59:11 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 4.1.1 win
Mar 06, 2024 11:59:11 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
Mar 06, 2024 11:59:13 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Mar 06, 2024 11:59:14 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 1. Refreshed file cache:3000 files. [] took 656 ms. to complete.
Mar 06, 2024 11:59:14 PM org.openaudible.library.BookLibrary load
INFO: Loading P:\Plex Extra\OpenAudibleFiles\books.json length 7263514
Mar 06, 2024 11:59:15 PM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Mar 06, 2024 11:59:17 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 2. Refreshed file cache:3000 files. [] took 739 ms. to complete.
Mar 06, 2024 11:59:17 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 4118 ms. to complete.
Mar 06, 2024 11:59:20 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Mar 06, 2024 11:59:40 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Download
Mar 06, 2024 11:59:40 PM org.openaudible.desktop.swt.manager.AudibleGUI downloadAAX
INFO: Added 1 of 1
Mar 06, 2024 11:59:40 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job Download Dragon Emperor 7: Human to Drago DownloadQueue size:1 remain:0 success:0 fail:0 threads:1 jobs:0
Mar 06, 2024 11:59:40 PM org.openaudible.util.queues.ThreadedQueue jobStarted
INFO: DownloadQueue started:Dragon Emperor 7: Human to Drago DownloadQueue size:1 remain:0 success:0 fail:0 threads:1 jobs:1
Mar 06, 2024 11:59:42 PM org.openaudible.audible.api.Client requestBytes
WARNING: error getting: https://api.audible.co.uk/1.0/content/B0876FTPBJ/licenserequest -> Not Found {"message":"Missing product attributes in Catalog datapath response."}
Mar 06, 2024 11:59:42 PM org.openaudible.audible.api.API getLicenseForBook
WARNING: Error with license request for book asin=B0876FTPBJ path=/content/B0876FTPBJ/licenserequest req={"consumption_type":"Download","supported_drm_types":["Mpeg","Adrm"],"response_groups":"last_position_heard, pdf_url, content_reference, chapter_info","quality":"High"} lr=null [this log msg may contain personally identifying information and should be kept private]
Mar 06, 2024 11:59:42 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download Dragon Emperor 7: Human to Drago item Dragon Emperor 7: Human to Drago
java.io.IOException: http error getting: https://api.audible.co.uk/1.0/content/B0876FTPBJ/licenserequest reason:Not Found error {"message":"Missing product attributes in Catalog datapath response."}
	at org.openaudible.audible.api.Client.requestBytes(Client.java:179)
	at org.openaudible.audible.api.Client.request(Client.java:97)
	at org.openaudible.audible.api.Client.post(Client.java:91)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:603)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:590)
	at org.openaudible.audible.APIManager.getAAXCDownloadLink(APIManager.java:101)
	at org.openaudible.download.DownloadAAXJob.preProcessAAXC(DownloadAAXJob.java:281)
	at org.openaudible.download.DownloadAAXJob.downloadAlt(DownloadAAXJob.java:222)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:234)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:571)

Mar 06, 2024 11:59:42 PM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:Dragon Emperor 7: Human to Drago DownloadQueue size:0 remain:0 success:0 fail:1 threads:1 jobs:0
Mar 06, 2024 11:59:47 PM org.openaudible.queues.JobProgressManager lambda$setDone$0
SEVERE: JobStatusManager: job not removed: download Dragon Emperor 7: Human to Drago Error done
Mar 06, 2024 11:59:53 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Manage_Accounts
Mar 06, 2024 11:59:56 PM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Mar 07 00:57:29 AEST 2024 now=Wed Mar 06 23:59:54 AEST 2024 delta=57 minutes and 35 seconds
exp=Thu Mar 07 00:59:56 AEST 2024 now=Wed Mar 06 23:59:56 AEST 2024 delta=59 minutes and 59 seconds
Mar 06, 2024 11:59:58 PM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Mar 07 00:57:34 AEST 2024 now=Wed Mar 06 23:59:56 AEST 2024 delta=57 minutes and 37 seconds
exp=Thu Mar 07 00:59:58 AEST 2024 now=Wed Mar 06 23:59:58 AEST 2024 delta=59 minutes and 59 seconds
Mar 07, 2024 12:00:00 AM org.openaudible.audible.api.API renewCredentials
INFO: exp=Thu Mar 07 00:57:32 AEST 2024 now=Wed Mar 06 23:59:58 AEST 2024 delta=57 minutes and 33 seconds
exp=Thu Mar 07 01:00:00 AEST 2024 now=Thu Mar 07 00:00:00 AEST 2024 delta=59 minutes and 59 seconds
Mar 07, 2024 12:00:11 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Mar 07, 2024 12:00:54 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Quick_Refresh
Mar 07, 2024 12:00:54 AM org.openaudible.audible.LibraryScanner library
INFO: getting library from API since Mon Feb 26 00:00:00 AEST 2024
Mar 07, 2024 12:00:57 AM org.openaudible.audible.LibraryScanner library
INFO: Successfully got 0 book(s) from library with since Mon Feb 26 00:00:00 AEST 2024
Mar 07, 2024 12:00:58 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 7263514 to disk:C:\Users\Lee Mackinnell\OpenAudible\tmp\saved_books.json
Mar 07, 2024 12:00:58 AM org.openaudible.library.BookLibrary save
INFO: Saved books P:\Plex Extra\OpenAudibleFiles\books.json length 7263514 took 1259 ms. to complete.
Mar 07, 2024 12:00:58 AM org.openaudible.audible.LibraryScanner library
INFO: getting library from API since Mon Feb 26 00:00:00 AEST 2024
Mar 07, 2024 12:01:00 AM org.openaudible.audible.LibraryScanner library
INFO: Successfully got 1 book(s) from library with since Mon Feb 26 00:00:00 AEST 2024
Mar 07, 2024 12:01:00 AM org.openaudible.util.queues.ThreadedQueue drain
INFO: Draining queue: MetaQueue size:1 remain:1 success:0 fail:0 threads:2 jobs:0
Mar 07, 2024 12:01:00 AM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job MetaJob Dirk Gently: Two BBC Radio Full- MetaQueue size:1 remain:0 success:0 fail:0 threads:1 jobs:0
Mar 07, 2024 12:01:00 AM org.openaudible.util.queues.ThreadedQueue jobStarted
INFO: MetaQueue started:Dirk Gently: Two BBC Radio Full- MetaQueue size:1 remain:0 success:0 fail:0 threads:1 jobs:1
Mar 07, 2024 12:01:04 AM org.openaudible.util.queues.ThreadedQueue drain
INFO: Drained queue: MetaQueue size:0 remain:0 success:1 fail:0 threads:0 jobs:0 in 4.31
Mar 07, 2024 12:01:04 AM org.openaudible.audible.LibraryScanner library
INFO: Scan of library complete. Books not in library:2337 meta errors:MetaQueue
Mar 07, 2024 12:01:04 AM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Mar 07, 2024 12:01:05 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 7263514 to disk:C:\Users\Lee Mackinnell\OpenAudible\tmp\saved_books.json
Mar 07, 2024 12:01:05 AM org.openaudible.library.BookLibrary save
INFO: Saved books P:\Plex Extra\OpenAudibleFiles\books.json length 7263514 took 1056 ms. to complete.
Mar 07, 2024 12:01:05 AM org.openaudible.audible.LibraryScanner library
INFO: getting library from API since Mon Feb 26 00:00:00 AEST 2024
Mar 07, 2024 12:01:08 AM org.openaudible.audible.LibraryScanner library
INFO: Successfully got 1 book(s) from library with since Mon Feb 26 00:00:00 AEST 2024
Mar 07, 2024 12:01:08 AM org.openaudible.util.queues.ThreadedQueue drain
INFO: Draining queue: MetaQueue size:1 remain:1 success:0 fail:0 threads:2 jobs:0
Mar 07, 2024 12:01:08 AM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job MetaJob Dirk Gently: Two BBC Radio Full- MetaQueue size:1 remain:0 success:0 fail:0 threads:2 jobs:0
Mar 07, 2024 12:01:08 AM org.openaudible.util.queues.ThreadedQueue jobStarted
INFO: MetaQueue started:Dirk Gently: Two BBC Radio Full- MetaQueue size:1 remain:0 success:0 fail:0 threads:1 jobs:1
Mar 07, 2024 12:01:11 AM org.openaudible.util.queues.ThreadedQueue drain
INFO: Drained queue: MetaQueue size:0 remain:0 success:1 fail:0 threads:0 jobs:0 in 3.069
Mar 07, 2024 12:01:11 AM org.openaudible.audible.LibraryScanner library
INFO: Scan of library complete. Books not in library:2337 meta errors:MetaQueue
Mar 07, 2024 12:01:11 AM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Mar 07, 2024 12:01:12 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 7263521 to disk:C:\Users\Lee Mackinnell\OpenAudible\tmp\saved_books.json
Mar 07, 2024 12:01:12 AM org.openaudible.library.BookLibrary save
INFO: Saved books P:\Plex Extra\OpenAudibleFiles\books.json length 7263521 took 957 ms. to complete.
Mar 07, 2024 12:01:13 AM org.openaudible.desktop.swt.manager.AudibleGUI downloadAndConvertWithDialog
INFO: You have 67 books to download
You have 271 books to convert to MP3

 autoConvert=false
Mar 07, 2024 12:01:15 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:START_JOBS_TITLE body:You have 67 books to download
You have 271 books to convert to MP3

Would you like to start these tasks now? response:BUTTON_NO
Mar 07, 2024 12:01:20 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Mar 07, 2024 12:01:46 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Download
Mar 07, 2024 12:01:46 AM org.openaudible.desktop.swt.manager.AudibleGUI downloadAAX
INFO: Added 1 of 1
Mar 07, 2024 12:01:46 AM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job Download Dragon Emperor 7: Human to Drago DownloadQueue size:1 remain:0 success:0 fail:1 threads:1 jobs:0
Mar 07, 2024 12:01:46 AM org.openaudible.util.queues.ThreadedQueue jobStarted
INFO: DownloadQueue started:Dragon Emperor 7: Human to Drago DownloadQueue size:1 remain:0 success:0 fail:1 threads:1 jobs:1
Mar 07, 2024 12:01:48 AM org.openaudible.audible.api.Client requestBytes
WARNING: error getting: https://api.audible.co.uk/1.0/content/B0876FTPBJ/licenserequest -> Not Found {"message":"Missing product attributes in Catalog datapath response."}
Mar 07, 2024 12:01:48 AM org.openaudible.audible.api.API getLicenseForBook
WARNING: Error with license request for book asin=B0876FTPBJ path=/content/B0876FTPBJ/licenserequest req={"consumption_type":"Download","supported_drm_types":["Mpeg","Adrm"],"response_groups":"last_position_heard, pdf_url, content_reference, chapter_info","quality":"High"} lr=null [this log msg may contain personally identifying information and should be kept private]
Mar 07, 2024 12:01:48 AM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download Dragon Emperor 7: Human to Drago item Dragon Emperor 7: Human to Drago
java.io.IOException: http error getting: https://api.audible.co.uk/1.0/content/B0876FTPBJ/licenserequest reason:Not Found error {"message":"Missing product attributes in Catalog datapath response."}
	at org.openaudible.audible.api.Client.requestBytes(Client.java:179)
	at org.openaudible.audible.api.Client.request(Client.java:97)
	at org.openaudible.audible.api.Client.post(Client.java:91)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:603)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:590)
	at org.openaudible.audible.APIManager.getAAXCDownloadLink(APIManager.java:101)
	at org.openaudible.download.DownloadAAXJob.preProcessAAXC(DownloadAAXJob.java:281)
	at org.openaudible.download.DownloadAAXJob.downloadAlt(DownloadAAXJob.java:222)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:234)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:571)

Mar 07, 2024 12:01:48 AM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:Dragon Emperor 7: Human to Drago DownloadQueue size:0 remain:0 success:0 fail:2 threads:1 jobs:0
Mar 07, 2024 12:01:48 AM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Mar 07, 2024 12:01:52 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Mar 07, 2024 12:01:53 AM org.openaudible.queues.JobProgressManager lambda$setDone$0
SEVERE: JobStatusManager: job not removed: download Dragon Emperor 7: Human to Drago Error done

i do not know why it tries to get the book from the server it does, i think the easyist solution is to somehow specify the server to download the book from either automatically by checking the last 2 characters of the ASIN/SKU or manually specifying the server to get the book from
either specifying a single primary server in the accounts screen which i am unsure what the active servers checkbox does? or by prompting the user to select the server....

**Comment by feldegast** [comment]
i do not know why it tries to get the book from the server it does, i think the easyist solution is to somehow specify the server to download the book from either automatically by checking the last 2 characters of the ASIN/SKU or manually specifying the server to get the book from
either specifying a single primary server in the accounts screen which i am unsure what the active servers checkbox does? or by prompting the user to select the server....

**Comment by feldegast** [comment]
i think this is now resolved in the latest beta?
