### ISSUE TITLE
Recently upgraded, tracks aren't renamed to the new format in 1.5.3

### ISSUE THREAD

**Issue by jimschubert** [openaudible/openaudible#188]
OpenAudible prompts to rename to a new format:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/109659/64475202-807eee80-d14d-11e9-8e89-f5c466f47e4d.png">

The import fails with no clear indication as to why, and no real resolution steps:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/109659/64475211-a3a99e00-d14d-11e9-8291-888cce54aa5b.png">

Console shows this same exception, repeated:

```
Sep 07, 2019 8:51:58 AM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Unable to rename
java.lang.IllegalStateException: Invalid case
	at org.openaudible.Directories.getMediaFile(Directories.java:369)
	at org.openaudible.Audible.renameBookMediaFiles(Audible.java:996)
	at org.openaudible.desktop.swt.manager.AudibleGUI$7.run(AudibleGUI.java:1351)
```

Full top of the log until the repeats:

```
Sep 07, 2019 9:00:47 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/OpenAudible.app/Contents/java/app/bin/mac/ffmpeg -version 
Sep 07, 2019 9:00:47 AM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-89585-g5533cbf-tessus Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil      56.  6.100 / 56.  6.100
libavcodec     58.  8.100 / 58.  8.100
libavformat    58.  3.100 / 58.  3.100
libavdevice    58.  0.100 / 58.  0.100
libavfilter     7.  7.100 /  7.  7.100
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100

Sep 07, 2019 9:00:49 AM org.openaudible.desktop.swt.gui.MessageBoxFactory showGeneral
INFO: MessageDialog: title:NOTIFY_UPGRADE_TITLE body:This new version of OpenAudible uses a new file naming system.\n\nThe aax, mp3, and cover art files in the OpenAudible working directory will be renamed to use the book title instead of the product ID as file names.\n\nIf you wish to back up your OpenAudible library, you can do that now, or press 'No' to rename them later.\n\nProceed with file name update for 94 books? response:BUTTON_YES
Sep 07, 2019 9:00:49 AM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Unable to rename
java.lang.IllegalStateException: Invalid case
	at org.openaudible.Directories.getMediaFile(Directories.java:369)
	at org.openaudible.Audible.renameBookMediaFiles(Audible.java:996)
	at org.openaudible.desktop.swt.manager.AudibleGUI$7.run(AudibleGUI.java:1351)

Sep 07, 2019 9:00:49 AM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Unable to rename
java.lang.IllegalStateException: Invalid case
	at org.openaudible.Directories.getMediaFile(Directories.java:369)
	at org.openaudible.Audible.renameBookMediaFiles(Audible.java:996)
	at org.openaudible.desktop.swt.manager.AudibleGUI$7.run(AudibleGUI.java:1351)
```

If I wanted to manually rename, how would I go about finding the expected target name for the old files?

**Comment by jimschubert** [comment]
I've uninstalled 1.5.3, and installed 1.5.2. This converts the books, so it seems to be an issue with the conversion process in 1.5.3.

**Comment by openaudible** [comment]
That is a bug. Fixed for next release. Thanks for the report.
