### ISSUE TITLE
Getting this when trying to start Openaudible 1.5.5

### ISSUE THREAD

**Issue by GreentheGroovy1** [openaudible/openaudible#219]
java -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.gtk.linux.x86_64-4.6.jar" org.openaudible.desktop.Application
Oct 25, 2019 1:21:43 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 1.5.5 for gtk swt 4763 jvm 11.0.5
Oct 25, 2019 1:21:43 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 1.5.5 for gtk swt 4763 jvm 11.0.5
Oct 25, 2019 1:21:47 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.5.5
Oct 25, 2019 1:21:47 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.5.5
Oct 25, 2019 1:21:47 PM org.openaudible.Directories getPrefs
INFO: No prefs:/home/mcthenymichael/OpenAudible/settings.json
Oct 25, 2019 1:21:47 PM org.openaudible.Directories getPrefs
INFO: No prefs:/home/mcthenymichael/OpenAudible/settings.json
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
Exception in thread "main" org.eclipse.swt.SWTError: No more handles
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.browser.Browser.<init>(Unknown Source)
        at org.openaudible.desktop.swt.manager.views.SummaryPanel.<init>(SummaryPanel.java:34)
        at org.openaudible.desktop.swt.manager.views.MainWindow.createSummaryPanel(MainWindow.java:185)
        at org.openaudible.desktop.swt.manager.views.MainWindow.createTop(MainWindow.java:125)
        at org.openaudible.desktop.swt.manager.views.MainWindow.<init>(MainWindow.java:45)
        at org.openaudible.desktop.swt.manager.Application.createMainBody(Application.java:45)
        at org.openaudible.desktop.swt.manager.Application.createLayout(Application.java:55)
        at org.openaudible.desktop.swt.manager.Application.initComponents(Application.java:98)
        at org.openaudible.desktop.swt.gui.GUI.startUp(GUI.java:233)
        at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:62)
        at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:71)
        at org.openaudible.desktop.Application.main(Application.java:22)

**Comment by openaudible** [comment]
This looks related to #81. Basically, not all linux systems are compatible with the framework we use, which is eclipse swt, or specifically, SWT apps that use the SWT Browser. Googling "swt browser no more handles" leads to a hint that its related to XULRunner .. whatever that is. Unfortunately, I don't have the skills or inclination to fix it... but lots of people have ideas about what additional software should be installed or upgraded. Usually this bug turns up when the user opens the internal browser in OA...but we added a summary panel that renders the book descriptions in html... so it happens sooner now... so we will at least catch it sooner in the next release..

**Comment by openaudible** [comment]
Marking as "Won't fix". Sorry.

**Comment by GreentheGroovy1** [comment]
I found a workaround . I installed the epiphany browser. Now OpenAudible works just fine . Note that i also tried this with Firefox and Chrome and Midori. This did not fix this issue . it only worked with Epiphany . still looking into why but i'm just gad it works now
