### ISSUE TITLE
java.io.IOException: Cannot run program "nautilus": error=2, No such file or directory

### ISSUE THREAD

**Issue by MountainX** [openaudible/openaudible#288]
When running KDE, the default file browser is Dolphin. Most KDE users will not have Nautilus installed by default. From the logs:

```
INFO: Command: Preferences
Mar 09, 2020 9:37:28 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: nautilus --browser /home/computeruser/OpenAudible 
Mar 09, 2020 9:37:28 PM org.openaudible.desktop.swt.gui.GUI explore
SEVERE: /home/computeruser/OpenAudible
java.io.IOException: Cannot run program "nautilus": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.openaudible.util.SimpleProcess.run(SimpleProcess.java:46)
	at org.openaudible.util.SimpleProcess.getResults(SimpleProcess.java:112)
	at org.openaudible.desktop.swt.gui.GUI.explore(GUI.java:208)
	at org.openaudible.desktop.swt.manager.views.Preferences$3.widgetSelected(Preferences.java:250)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:820)
	at org.eclipse.jface.window.Window.open(Window.java:796)
	at org.openaudible.desktop.swt.manager.views.Preferences.show(Preferences.java:59)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:256)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:83)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:358)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:345)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:446)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:72)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:80)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.org.openaudible.desktop.Application.main(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 34 more
```

**Comment by openaudible** [comment]
I hard-coded nautilus because whatever else I tried didn't work.
Anyone know the cross-platform command to select a file in a directory on linux? (bash or java)

**Comment by MountainX** [comment]
> Anyone know the cross-platform command to select a file in a directory on linux? (bash or java)

I use `xdg-open`. Did you try that? You might have to have it within a conditional block that checks the OS / platform. But I would be happy to help test it on Linux.

I do not have a development environment set up. But I will look into downloading via git and building via the command line. 

> Build from command line (requires maven, java 8 SDK)

Would these packages be sufficient to build openaudible?

Arch Linux - maven 3.6.3-1 (any)
https://www.archlinux.org/packages/community/any/maven/

Arch Linux - jdk8-openjdk 8.u242-1 (x86_64)
https://www.archlinux.org/packages/extra/x86_64/jdk8-openjdk/

**Comment by openaudible** [comment]
Does xdg-open work on files or just directories? For instance, can you call `xdg-open /path/file.mp3` or do you have to just call `xdg-open /path`  The code is supposed to select the file inside of a directory.

It looks like a combination of guessing (kde->dolphin, gnome->nautilus, other->xdg-open) with an ability to add a preference for your own file explorer. 

I wouldn't bother trying to build the whole project.. the source code I have posted is not the most recent. But yes, java and maven are the two main apps. 

I'll play around a bit more. What's a decent KDE linux with dark mode I can install with an iso on VMWare?

**Comment by MountainX** [comment]
Thanks for your reply. For me `xdg-open /path/file.mp3` opens the MP3 file in my default audio player. `xdg-open /path/` opens that directory in my default file explorer, Dolphin. Those commands should open the default application like they do for me on any modern Linux system, whether KDE, Gnome or other.

I think any KDE will let you choose Breeze Dark as the theme. I'm running Arch Linux, but I don't guess you want to go through the trouble to install that. Maybe [Manjaro](https://wiki.manjaro.org/index.php)? It is the second most popular distro on DistroWatch, and I think the #1 most popular distro with KDE pre-installed. So that might be a good choice. A lot of people seem to like KDE Neon too.

I will help with testing or anything else I can help with.

**Comment by openaudible** [comment]
OK. I think that's why I can't use xdg-open because it doesn't select the file in the desktop.

 I think I have enough to work on. Trying kde neon.  Will let you know.

**Comment by openaudible** [comment]
Fixed for next release.. If which nautalis returns a path, we'll use nautalis, else if dolphin available, we'll use that.. then xdg-open as a last resort.

**Comment by openaudible** [comment]
Give 1.6.6 a try and see if it finds Dolphin. The log window should output what it is doing.
