### ISSUE TITLE
Unable to download or refresh library on 1.6.5

### ISSUE THREAD

**Issue by crowanon** [openaudible/openaudible#297]
As the title said I cannot download or refresh the library on 1.6.5

I have tried a fresh install of OpenAudible grabbed from this repo. 

One thing I have not tried is clearing all user settings, because I cannot find the folder for them.

Stacktrace from attempting to refresh library:
`
SEVERE: ProcessMenu: Rescan_Library
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1065)
	at org.openaudible.Audible.findOrphanedFiles(Audible.java:631)
	at org.openaudible.desktop.swt.manager.AudibleGUI.checkOrphansGUI(AudibleGUI.java:273)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshLibrary(AudibleGUI.java:344)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:277)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:83)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:358)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:345)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:446)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:72)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:80)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
`

Stack trace from attempting to download book:
`
SEVERE: runEventLoop (Unforseen Exception)
java.lang.NullPointerException
	at org.openaudible.Audible.importFromDownloadLink(Audible.java:1194)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.changing(BrowserWebClient.java:157)
	at org.eclipse.swt.browser.IE$7.handleEvent(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventSink.notifyListener(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventSink.Invoke(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventSink.access$100(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventSink$1.method6(Unknown Source)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:345)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:446)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:72)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:80)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
`

**Comment by crowanon** [comment]
I was able to download an AAX using ADM and extract it just fine. It was only OpenAudible that was the problem.

**Comment by openaudible** [comment]
That is a bug that I think has been fixed for the next release. Its part of code in "findOrphanedFiles" which looks for files in your mp3/aax folders that aren't in the displayed library.. so it doesn't happen much. Will close and make sure its fixed in the next version. Thanks.
