### ISSUE TITLE
Sync no lomger work with new Library format

### ISSUE THREAD

**Issue by OmegaRea** [openaudible/openaudible#299]
It looks like Audible has changed their Library page format and it will not sync with the program. I am able to download books already synced to my library, it just won't sync any new books as of this evening.

**Comment by openaudible** [comment]
Is there an error? Or something show in the console?

I just checked and it seems to be working fine on my development version.

**Comment by OmegaRea** [comment]
I bought several books in the past couple of days, but nothing shows up after the 24th. Here is the most recent log:

Mar 26, 2020 10:27:59 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 1.6.5 for win32 swt 4623 jvm 1.8.0_202 file charset UTF-8
Mar 26, 2020 10:27:59 PM org.openaudible.desktop.swt.gui.GUI <init>
SEVERE: Charset not set to utf-8
Mar 26, 2020 10:27:59 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.6.5
Mar 26, 2020 10:27:59 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1574295158656
Mar 26, 2020 10:28:00 PM org.openaudible.Audible load
INFO: Loading I:\Downloads\books.json
Mar 26, 2020 10:28:00 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1574295158656
Mar 26, 2020 10:28:00 PM org.openaudible.Audible checkLibrary
INFO: loaded 1099 books.
Mar 26, 2020 10:28:01 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 925 ms. to complete.
Mar 26, 2020 10:28:10 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Mar 26, 2020 10:28:11 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Mar 26, 2020 10:28:12 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
Mar 26, 2020 10:28:12 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
Mar 26, 2020 10:28:20 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Rescan_Library
Mar 26, 2020 10:28:20 PM org.openaudible.desktop.swt.manager.menu.CommandCenter handleMenuAction
SEVERE: ProcessMenu: Rescan_Library
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.addAll(Unknown Source)
	at org.openaudible.Audible.findOrphanedFiles(Audible.java:631)
	at org.openaudible.desktop.swt.manager.AudibleGUI.checkOrphansGUI(AudibleGUI.java:273)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshLibrary(AudibleGUI.java:344)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:277)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:83)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:358)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:345)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:446)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:72)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:80)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

Mar 26, 2020 10:28:42 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by OmegaRea** [comment]
UPDATE:  I just did an uninstall/reinstall, this seems to have fixed the problem.  it is syncing properly.

**Comment by openaudible** [comment]
This is the "findOrphanedFiles" that will be fixed in the next release. Thanks for the report.

**Comment by OmegaRea** [comment]
You are Welcome
