### ISSUE TITLE
Cannot Download or sync books 1.6.6

### ISSUE THREAD

**Issue by Gopher243** [openaudible/openaudible#305]
I am new to using OpenAudible and am not able to sync my library or download any books.

Console Code when attempting a quick sync:
Mar 31, 2020 2:26:59 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Quick_Refresh
Mar 31, 2020 2:26:59 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: ******************* LIBRARY PAGE 1
Mar 31, 2020 2:26:59 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:https://www.audible.com/lib
Mar 31, 2020 2:26:59 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFO:  getPage:https://www.audible.com/lib js=true
Mar 31, 2020 2:27:02 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
INFO: 0:getPage:https://www.audible.com/lib completed 2381 ms
02:26:59.777	07:00:00.003	waitForPageLoad:start
02:27:00.345	07:00:00.571	browser state unknown -> loading
02:27:01.824	07:00:02.050	event:LocChanged -> LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/library/titles top=true doit=false}
02:27:01.824	07:00:02.050	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=0 total=0}
02:27:02.002	07:00:02.228	browser state loading -> complete
02:27:02.002	07:00:02.228	needQuery: last=0 new=2
02:27:02.155	07:00:02.381	query start: end:h_len=608922 hash=9D086CDB eq=false Last Query:153;ProgChanged:6ProgComplete:1LocChanging:0LocChanged:1;same=0;diff=0;url=https://www.audible.com/lib
02:27:02.155	07:00:02.381	waitForPageLoad exit:2378 result=h_len=608922 hash=9D086CDB inspect=Last Query:153;ProgChanged:6ProgComplete:1LocChanging:0LocChanged:1;same=0;diff=1;url=https://www.audible.com/lib
Mar 31, 2020 2:27:02 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 939 to disk:C:\Users\Rachel\OpenAudible\tmp\0.txt
Mar 31, 2020 2:27:03 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 404585 to disk:C:\Users\Rachel\OpenAudible\tmp\no_lib_table.html
Mar 31, 2020 2:27:03 PM org.openaudible.util.HTMLUtil debugHtml
INFO: Debug: C:\Users\Rachel\OpenAudible\tmp\no_lib_table.html
Mar 31, 2020 2:27:03 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: pageNum=1 total=0 new=0 partial=0 hasNextPage=true
 error=no library table found Parsed:0 books

Mar 31, 2020 2:27:03 PM org.openaudible.Audible updateLibrary
INFO: Updated 0 books
Mar 31, 2020 2:27:03 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 2 to disk:C:\Users\Rachel\OpenAudible\tmp\saved_books.json
Mar 31, 2020 2:27:03 PM org.openaudible.Audible save
INFO: Save books took 4 ms. to complete.

Console Code when attempting to download from the browser:
Mar 31, 2020 2:28:36 PM org.openaudible.audible.parser.LibraryParser parseDownloadURL
INFO: converted The%20Time%20of%20Contempt to The Time of Contempt
Mar 31, 2020 2:28:36 PM org.openaudible.Audible importFromDownloadLink
INFO: Clicked download link:product_id=BK_HACH_005589,title=The Time of Contempt,download_link=https://cds.audible.com/download/admhelper?user_id=xxxx-ajWPpN-xxxx-t35pQ&product_id=BK_HACH_005589&domain=www.audible.com&cust_id=546cLMMeicQpDybkVthfb0DWnL-ajWPpN-s6L7m7j5idn01a7IPFYKH0-t35pQ&DownloadType=Now&transfer_player=1&codec=LC_128_44100_Stereo&awtype=AAX&title=The%20Time%20of%20Contempt,
Mar 31, 2020 2:28:36 PM org.openaudible.desktop.swt.gui.GUI logCritical
SEVERE: runEventLoop (Unforseen Exception)
java.lang.NullPointerException
	at org.openaudible.Audible.importFromDownloadLink(Audible.java:1224)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.changing(BrowserWebClient.java:174)
	at org.eclipse.swt.browser.IE$7.handleEvent(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventSink.notifyListener(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventSink.Invoke(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventSink.access$100(Unknown Source)
	at org.eclipse.swt.ole.win32.OleEventSink$1.method6(Unknown Source)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:394)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:495)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:72)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:80)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

Mar 31, 2020 2:28:36 PM org.openaudible.desktop.swt.gui.GUI logCritical
SEVERE: java.lang.NullPointerException

I attempted to go back to a previous version (1.6) and had the same issues. Any advice?

**Comment by openaudible** [comment]
That's a bug on our end. Looks like you clicked a "download" button on the web browser.. but the book isn't in your OA library. If possible, try downloading from the OA app by selecting the file and 'Download' action.
 
Thanks for finding it. Will be fixed in next version.

**Comment by openaudible** [comment]
Thanks for the report. Looks like audible changed their library view, breaking OpenAudible. Will track this in #306
