### ISSUE TITLE
Unable to interact with integrated Browser

### ISSUE THREAD

**Issue by TobeSoftwareGmbH** [openaudible/openaudible#313]
Hi there
I'm using Manjaro Linux (using jre8), just installed openaudible and attempted to login - however, the integrated web browser does not react to interactions. (clicks, scrolling, etc.) Furthermore, it unexpectedly turns gray when focussing another window, only seeing the web page again when hitting the "refresh" button. I'm not sure what the issue might be, but here is the console output:

> SEVERE: connectTask failed to log in: 
> org.openaudible.audible.AudibleLoginError: Not logged in:AudiblePage:https://www.audible.com/lib 0 bytes html
>         at org.openaudible.audible.AudibleScraper.throwNotLoggedIn(AudibleScraper.java:232)
>         at org.openaudible.audible.AudibleScraper.lib(AudibleScraper.java:199)
>         at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:510)
>         at org.openaudible.desktop.swt.manager.AudibleGUI.connectTask(AudibleGUI.java:410)
>         at org.openaudible.desktop.swt.manager.AudibleGUI$2.run(AudibleGUI.java:430)
> 
> 
> (WebKitWebProcess:60450): Gtk-WARNING **: 11:52:31.351: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (WebKitWebProcess:60450): Gtk-WARNING **: 11:52:31.351: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (WebKitWebProcess:60450): Gtk-WARNING **: 11:52:31.351: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (WebKitWebProcess:60450): Gtk-WARNING **: 11:52:31.351: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (WebKitWebProcess:60450): Gdk-ERROR **: 11:52:31.842: The program 'WebKitWebProcess' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'BadValue (integer parameter out of range for operation)'.
>   (Details: serial 227 error_code 2 request_code 151 (GLX) minor_code 34)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the GDK_SYNCHRONIZE environment
>    variable to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)

I know that this is probably not helpful, so please let me know if it's not and how I can get "valuable" information for you to fix the issue!

**Comment by TobeSoftwareGmbH** [comment]
Nevermind, just restarted my system and that fixed the issue
