### ISSUE TITLE
Refreshing library book name failure

### ISSUE THREAD

**Issue by evotodi** [openaudible/openaudible#378]
Version: 2.0.9

Issue:
When refreshing (quick or full) library I get a book name failure on page 3. All books on page 3 were added to audible in 2019. All books on page 3 were also downloaded by OpenAudible pre version 2.0.6

log:
```INFO: ******************* LIBRARY PAGE 3
May 27, 2020 5:48:03 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:
to: https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3
fr:htmlPage(https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=ZP1SNG1F00KXWK8HVJZ3&page=2) html length:748812
May 27, 2020 5:48:03 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: getPage https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3 fetchHTML=true
May 27, 2020 5:48:03 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFO:  getPage:https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3 js=true
May 27, 2020 5:48:03 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: changing LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3 top=false doit=true}
May 27, 2020 5:48:05 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: changed LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3 top=true doit=false}
May 27, 2020 5:48:05 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: task completed event:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
May 27, 2020 5:48:06 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
INFO: 0:getPage:https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3 completed 2307 ms
05:48:03.820	07:00:00.000	waitForPageLoad:start
05:48:04.322	07:00:00.502	browser state unknown -> loading
05:48:05.524	07:00:01.704	event:LocChanged -> LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3 top=true doit=false}
05:48:05.524	07:00:01.704	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=0 total=0}
05:48:05.940	07:00:02.120	browser state loading -> complete
05:48:05.940	07:00:02.120	needQuery: last=0 new=2
05:48:06.127	07:00:02.307	query start:h_len=0 hash=0 end:h_len=750926 hash=95778EEA eq=false Last Query:187;ProgChanged=5,ProgComplete=1,LocChanging=0,LocChanged=1,;same=0;diff=0;url=https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3
05:48:06.127	07:00:02.307	pageGood..exiting in 10 seconds...
05:48:06.127	07:00:02.307	waitForPageLoad exit:2307 result=h_len=750926 hash=95778EEA inspect=Last Query:187;ProgChanged=5,ProgComplete=1,LocChanging=0,LocChanged=1,;same=0;diff=1;url=https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3
May 27, 2020 5:48:06 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 1491 to disk:C:\Users\Justin\OpenAudible\tmp\0.txt
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper setURL
INFO: got page:htmlPage(https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=fb5f748e-1179-4c2d-a202-1d82c5cbea06&pf_rd_r=EWWDRPMWCQF91744YHRS&page=3) html length:750926 took 2307 ms. to complete.
May 27, 2020 5:48:06 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Library page contains: 20 book(s)
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.40
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.41
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.42
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.43
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.44
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.45
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.46
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.47
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.48
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap takeBook
INFO: File name collision: Purchase Options and Purchase Options.49
May 27, 2020 5:48:06 PM org.openaudible.audible.AudibleScraper takePageResults
INFO: Book changed:[download_link] for book:Purchase Options
May 27, 2020 5:48:06 PM org.openaudible.audible.FileNameMap handleCollision
SEVERE: Expected book in name map:asin_1705209467
May 27, 2020 5:48:06 PM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Error refreshing library
java.lang.IllegalStateException: book name failure!
	at org.openaudible.audible.FileNameMap.handleCollision(FileNameMap.java:158)
	at org.openaudible.audible.FileNameMap.takeBook(FileNameMap.java:53)
	at org.openaudible.audible.FileNameMap.getFileNameAndSet(FileNameMap.java:188)
	at org.openaudible.Audible.getFileName(Audible.java:1001)
	at org.openaudible.Audible.getFileDest(Audible.java:1374)
	at org.openaudible.Audible.hasFile(Audible.java:946)
	at org.openaudible.Audible.hasConverted(Audible.java:939)
	at org.openaudible.Audible.takeBook(Audible.java:332)
	at org.openaudible.audible.AudibleScraper.takePageResults(AudibleScraper.java:298)
	at org.openaudible.audible.AudibleScraper.rescanLibrary(AudibleScraper.java:416)
	at org.openaudible.desktop.swt.manager.AudibleGUI$1.run(AudibleGUI.java:367)

May 27, 2020 5:48:06 PM org.openaudible.desktop.swt.manager.AudibleGUI showError
SEVERE: refreshing library
java.lang.IllegalStateException: book name failure!
	at org.openaudible.audible.FileNameMap.handleCollision(FileNameMap.java:158)
	at org.openaudible.audible.FileNameMap.takeBook(FileNameMap.java:53)
	at org.openaudible.audible.FileNameMap.getFileNameAndSet(FileNameMap.java:188)
	at org.openaudible.Audible.getFileName(Audible.java:1001)
	at org.openaudible.Audible.getFileDest(Audible.java:1374)
	at org.openaudible.Audible.hasFile(Audible.java:946)
	at org.openaudible.Audible.hasConverted(Audible.java:939)
	at org.openaudible.Audible.takeBook(Audible.java:332)
	at org.openaudible.audible.AudibleScraper.takePageResults(AudibleScraper.java:298)
	at org.openaudible.audible.AudibleScraper.rescanLibrary(AudibleScraper.java:416)
	at org.openaudible.desktop.swt.manager.AudibleGUI$1.run(AudibleGUI.java:367)

May 27, 2020 5:48:06 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: MESSAGE_BOX_TITLE_ERROR
Error
May 27, 2020 5:48:06 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Audible Library Update...} visible=true input shell:Shell {OpenAudible}
```

OpenAudible Browser Page 3:

![Screenshot_2020-05-27 My Library Audible com](https://user-images.githubusercontent.com/1625853/83076799-31af1700-a044-11ea-8bea-b7acb6898aec.jpg)

**Comment by openaudible** [comment]
Try version 2.1. Audible seems to have made a change for some regions that we didn't have a parser for to get the title. 
If that doesn't work, you may need to recreate your library... or possibly remove books that appear to be duplicates or causing those problems.

**Comment by rloomans** [comment]
I've got the same problem (Mac OS X 10.15.5, OpenAudible 2.1)

I deleted the ~/Library/OpenAudible directory, retried and got the same result.

**Comment by evotodi** [comment]
Upgraded to OpenAudible 2.1 but still had the same issue of book name failure. Deleted the books.json file and started OpenAudible then started a full sync. It asked to import the found books so I answered yes. OA proceeded to import 1048 titles which is 524 aax files and 524 mp3 files. After that completed it got to page 3 of scraping audible and failed with book name failure.

What I noticed was after deleting books.json and starting OA then connecting to audible, OA first filled the books panel with 20 books named Purchase Options then proceeded to update each line with the data for the first 20 books in my audible library.

Why did it scrape audible's first page upon connecting and populate the books panel with bad data for the first 20 books?

How about a command to regenerate the library? Something that clears the books.json and clears the books in memory then imports downloaded books and syncs with audible.

What I do not want to do is delete 524 aax files and 524 mp3 files then redownload and convert them all to mp3 again. If there is anything I can help with or provide information on feel free to contact me.

Initial books.json exerpt:
(filename key is sequential Purchase Options.1-19)
```
{
  "summary": "<p><b>Audible number-one best seller Peter Clines returns with a thrilling tale of the creature above - and the deadly threat below.<\/b> <\/p>\n<p>In the year 2243, the Moon belongs to the dead. <\/p>\n<p>The largest graveyard in the solar system, it was the perfect solution to the overcrowding and environmental problems that had plagued mankind for centuries. And the perfect place for Cali Washington to run away from her past. <\/p>\n<p>But when a mysterious meteor crashes into one of the Moon\u2019s cemeteries, Cali and her fellow Caretakers find themselves surrounded by a terrifying enemy force that outnumbers them more than a thousand to one. An enemy not hindered by the lack of air or warmth or sustenance. <\/p>\n<p>An enemy that is already dead. <\/p>\n<p>Now Cali and her compatriots must fight to survive. Because if they don\u2019t, everyone on the Moon may be joining the dead. <\/p>\n<p>And maybe everyone on Earth, too....<\/p>",
  "rating_average": "4.056370656370657",
  "author": "Peter Clines",
  "series_link": "/series/Threshold-Series-Audiobooks/B07CTLQHD",
  "language": "english",
  "title": "Purchase Options",
  "info_link": "https://www.audible.com/pd/Dead-Moon-Audiobook/B07MS6267K",
  "rating_count": "5180",
  "duration": "11:23:00",
  "author_link": "https://www.audible.com/author/Peter-Clines/B0039LGSLW",
  "download_link": "https://cds.audible.com/download/admhelper?user_id=msuKOph9VarnTAR5aoIT_kBe2XecPJaLGth73keBmSo4a7aps2lPB1vnnUY__g&product_id=OR_ORIG_000309&domain=www.audible.com&cust_id=msuKOph9VarnTAR5aoIT_kBe2XecPJaLGth73keBmSo4a7aps2lPB1vnnUY__g&DownloadType=Now&transfer_player=1&codec=LC_128_44100_Stereo&awtype=AAX&title=Dead Moon",
  "filename": "Purchase Options.6",
  "narrated_by": "Ray Porter",
  "release_date": "2019-02-14",
  "product_id": "OR_ORIG_000309",
  "genre": "Science Fiction & Fantasy:Science Fiction",
  "publisher": "Audible Original",
  "asin": "B07MS6267K",
  "purchase_date": "04-17-20"
 },
```

AAX Metadata for the above book:
![meta](https://user-images.githubusercontent.com/1625853/83141394-978bb500-a0bd-11ea-91e8-a722a3f58c62.jpg)

OA just after connecting to audible:
![PurchaseOptions](https://user-images.githubusercontent.com/1625853/83139279-1bdc3900-a0ba-11ea-8269-543352ec5705.jpg)

OA filling in book data for first 20 books in audible library:
![PurchaseOptionsFilling](https://user-images.githubusercontent.com/1625853/83139339-344c5380-a0ba-11ea-89a3-0aa09d375dde.jpg)

OA Preferences:
![Prefs](https://user-images.githubusercontent.com/1625853/83139381-44643300-a0ba-11ea-94c0-6b55d25a42d2.jpg)


What i found that DID NOT work:
- First delete books.json
- Start OA and connect to audible then allow it to finish scraping the first 20 books.
- Select all books in the panel then delete them with Controls->Delete
- Delete books.json again along with tmp/saved_books.json and tmp/*.html
- Start a full sync and click yes to import

**Comment by openaudible** [comment]
Ok. Thank you for your reports. Have it reproduced here. Looks like a change in the audible html format.

The title has been moved from its usual place and replaced with the words "Purchase Options". This is causing the problem.

I'm working on a fix. 

In the future, if you send a bug report from the about menu after seeing a problem, that makes it easy to reproduce-- sometimes new web changes are rolled out slowly so I don't see them.

Are your filenames also "Purchase Options"? I'll probably have to delete all files that include that name...

**Comment by evotodi** [comment]
No all file names are good. And meta data on the aax files look good also.

**Comment by openaudible** [comment]
Posted new version 2.1.1. Let me know if working. You'll need to delete any books with incorrect titles.

**Comment by OmegaRea** [comment]
I had the same probelm and this seemed to fix it for me.

**Comment by evotodi** [comment]
Fixed for me also. I removed books.json and tmp folder before opening 2.1.1.
Thank you for the fix.

**Comment by rloomans** [comment]
Works again for me too
