### ISSUE TITLE
Console Window does not open

### ISSUE THREAD

**Issue by Erudition** [openaudible/openaudible#38]
File > Console silently fails.

When running from the CLI, one can see the silently ignored exceptions:
```
Oct 05, 2018 4:08:39 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Oct 05, 2018 4:08:39 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Oct 05, 2018 4:08:39 PM org.openaudible.desktop.swt.manager.menu.CommandCenter handleMenuAction
SEVERE: ProcessMenu: Console
java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.widgets.Widget.error(Unknown Source)
        at org.eclipse.swt.widgets.Decorations.setImages(Unknown Source)
        at org.openaudible.desktop.swt.manager.views.LogWindow.<init>(LogWindow.java:58)
        at org.openaudible.desktop.swt.manager.views.LogWindow.show(LogWindow.java:37)
        at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:260)
        at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:62)
        at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:304)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:332)
        at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:428)
        at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:54)
        at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:62)
        at org.openaudible.desktop.Application.main(Application.java:8)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)

Oct 05, 2018 4:08:39 PM org.openaudible.desktop.swt.manager.menu.CommandCenter handleMenuAction
SEVERE: ProcessMenu: Console
java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.widgets.Widget.error(Unknown Source)
        at org.eclipse.swt.widgets.Decorations.setImages(Unknown Source)
        at org.openaudible.desktop.swt.manager.views.LogWindow.<init>(LogWindow.java:58)
        at org.openaudible.desktop.swt.manager.views.LogWindow.show(LogWindow.java:37)
        at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:260)
        at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:62)
        at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:304)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:332)
        at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:428)
        at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:54)
        at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:62)
        at org.openaudible.desktop.Application.main(Application.java:8)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
```

**Comment by openaudible** [comment]
Hmm. Didn't catch that in time for 1.2. Give it a try and if its still not working, I think I can fix it for next release. Thanks.

**Comment by mwalter416** [comment]
Same issue, running on 18.04 with 1.2.6 release.

**Comment by Dekken** [comment]
seeing this with 1.3 on Ubuntu 18.04
