### ISSUE TITLE
Doesn't connect (AudibleLoginError) despite being logged in

### ISSUE THREAD

**Issue by Erudition** [openaudible/openaudible#39]
The previous bug #20  was closed prematurely with a dev saying only that it's "supposed to work", along with suggesting the browser must not have been logged in. However, it still doesn't work, for me at least - and I've updated to the latest version. They suggested looking under the Log window, however, that does not work either, so I filed bug #38 . They said "look for any human readable error", but there seems to be no errors when using the Browser. Starting from the CLI I can see the log messages when using the browser:

```
Oct 05, 2018 4:17:55 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Browser
Oct 05, 2018 4:17:55 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Browser
ignore non-audible...www.amazon.com
Oct 05, 2018 4:18:14 PM org.openaudible.audible.ConnectionNotifier setLastURL
INFO: Setting lastURL to:https://www.audible.com/lib?serial=&
Oct 05, 2018 4:18:14 PM org.openaudible.audible.ConnectionNotifier setLastURL
INFO: Setting lastURL to:https://www.audible.com/lib?serial=&
Oct 05, 2018 4:18:45 PM org.openaudible.audible.ConnectionNotifier setLastURL
INFO: Setting lastURL to:https://www.audible.com/access
Oct 05, 2018 4:18:45 PM org.openaudible.audible.ConnectionNotifier setLastURL
INFO: Setting lastURL to:https://www.audible.com/access
Oct 05, 2018 4:19:01 PM org.openaudible.audible.ConnectionNotifier setLastURL
INFO: Setting lastURL to:https://www.audible.com/lib
Oct 05, 2018 4:19:01 PM org.openaudible.audible.ConnectionNotifier setLastURL
INFO: Setting lastURL to:https://www.audible.com/lib
```
As you can see, I tried three different URLs. But it just sat there, logged in. 

So I backed out and tried "Connect". I guess it failed, because it still brought me back to a browser (which was still signed in, showing my library). 

However, this time I caught some errors that may be of assistance!
```
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Oct 05, 2018 4:20:52 PM org.openaudible.audible.AudibleScraper loadCookies
INFO: Loaded 14 cookies
Oct 05, 2018 4:20:52 PM org.openaudible.audible.AudibleScraper loadCookies
INFO: Loaded 14 cookies
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Setting cookies 1
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Setting cookies 1
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 2
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 2
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 3
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 3
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Done Setting cookies 4
Oct 05, 2018 4:20:52 PM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Done Setting cookies 4
Oct 05, 2018 4:20:52 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:https://www.audible.com/
Oct 05, 2018 4:20:52 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:https://www.audible.com/
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sourceforge.htmlunit.corejs.javascript.NativeArray (file:/home/adroit/Software/OpenAudible/openaudible-jar-with-dependencies.jar) to field java.util.Arrays$LegacyMergeSort.userRequested
WARNING: Please consider reporting this to the maintainers of net.sourceforge.htmlunit.corejs.javascript.NativeArray
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: TypeError: Symbol is not a constructor (script in https://www.audible.com/ from (153447, 17) to (153533, 10)#22417) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
https://images-na.ssl-images-amazon.com/images/I/61KiPjbnB6L.js?AUIClients/AudibleBrickCitySkin
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "XML" is not defined. (https://images-na.ssl-images-amazon.com/images/I/61KiPjbnB6L.js?AUIClients/AudibleBrickCitySkin#1) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
https://images-na.ssl-images-amazon.com/images/I/21Es6CabSIL.js?AUIClients/AudibleWebNavigationAssets
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "XML" is not defined. (https://images-na.ssl-images-amazon.com/images/I/21Es6CabSIL.js?AUIClients/AudibleWebNavigationAssets#1) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
https://images-na.ssl-images-amazon.com/images/I/21nv4Y851zL.js?AUIClients/AryaAnalyticsAssets
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "XML" is not defined. (https://images-na.ssl-images-amazon.com/images/I/21nv4Y851zL.js?AUIClients/AryaAnalyticsAssets#1) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
https://images-na.ssl-images-amazon.com/images/I/11zWgMhoR6L.js?AUIClients/AudibleWebSearchAssets
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "XML" is not defined. (https://images-na.ssl-images-amazon.com/images/I/11zWgMhoR6L.js?AUIClients/AudibleWebSearchAssets#1) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: Exception invoking observe of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
https://images-na.ssl-images-amazon.com/images/G/01/Audible/res/script/DTM/dtm_common.js
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "XML" is not defined. (https://images-na.ssl-images-amazon.com/images/G/01/Audible/res/script/DTM/dtm_common.js#1) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
https://images-na.ssl-images-amazon.com/images/G/01/Audible/res/script/DTM/843e2f5b8ab495a5f828c0b9302ff13fbaff1d33/satelliteLib-ee5a1f44328252330249a0e25cbda71e7dfe44b4.js
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "XML" is not defined. (https://images-na.ssl-images-amazon.com/images/G/01/Audible/res/script/DTM/843e2f5b8ab495a5f828c0b9302ff13fbaff1d33/satelliteLib-ee5a1f44328252330249a0e25cbda71e7dfe44b4.js#1) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
https://images-na.ssl-images-amazon.com/images/G/01/AUIClients/ClientSideMetricsAUIJavascript@jserrorsForesterSushi.46c6cbcede0c7c688c9853fd064e69c3dffdcb2e._V2_.js
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "XML" is not defined. (https://images-na.ssl-images-amazon.com/images/G/01/AUIClients/ClientSideMetricsAUIJavascript@jserrorsForesterSushi.46c6cbcede0c7c688c9853fd064e69c3dffdcb2e._V2_.js#1) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
https://m.media-amazon.com/images/G/01/csm/showads.v2.js
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "XML" is not defined. (https://m.media-amazon.com/images/G/01/csm/showads.v2.js#1) of class com.gargoylesoftware.htmlunit.ScriptException where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
Oct 05, 2018 4:20:56 PM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.audible.com/ Audible.com - Over 425,000 of the Best Audiobooks & Original Content
Oct 05, 2018 4:20:56 PM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.audible.com/ Audible.com - Over 425,000 of the Best Audiobooks & Original Content
Oct 05, 2018 4:20:57 PM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /home/adroit/OpenAudible/tmp/checkLoggedIn.html
Oct 05, 2018 4:20:57 PM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /home/adroit/OpenAudible/tmp/checkLoggedIn.html
Oct 05, 2018 4:20:57 PM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /home/adroit/OpenAudible/tmp/checkLoggedIn.html
Oct 05, 2018 4:20:57 PM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /home/adroit/OpenAudible/tmp/checkLoggedIn.html
Oct 05, 2018 4:20:57 PM org.openaudible.desktop.swt.manager.AudibleGUI connect
SEVERE: unable to connect
org.openaudible.audible.AudibleLoginError
        at org.openaudible.audible.AudibleScraper.home(AudibleScraper.java:336)
        at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:380)
        at org.openaudible.desktop.swt.manager.AudibleGUI.access$000(AudibleGUI.java:44)
        at org.openaudible.desktop.swt.manager.AudibleGUI$2.run(AudibleGUI.java:257)

Oct 05, 2018 4:20:57 PM org.openaudible.desktop.swt.manager.AudibleGUI connect
SEVERE: unable to connect
org.openaudible.audible.AudibleLoginError
        at org.openaudible.audible.AudibleScraper.home(AudibleScraper.java:336)
        at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:380)
        at org.openaudible.desktop.swt.manager.AudibleGUI.access$000(AudibleGUI.java:44)
        at org.openaudible.desktop.swt.manager.AudibleGUI$2.run(AudibleGUI.java:257)

Oct 05, 2018 4:20:58 PM org.openaudible.audible.ConnectionNotifier setLastURL
INFO: Setting lastURL to:https://www.audible.com/
Oct 05, 2018 4:20:58 PM org.openaudible.audible.ConnectionNotifier setLastURL
INFO: Setting lastURL to:https://www.audible.com/
```

**Comment by openaudible** [comment]
Give 1.2 a try. If any problems, please create a new ticket. The new 1.2 has a whole new way of connecting.
