### ISSUE TITLE
Cannot find checksum when converting from aax

### ISSUE THREAD

**Issue by bookworm45** [openaudible/openaudible#408]
When trying to convert aax file I get an error message saying that checksum file cannot be found. Please see console log below.

```
Jun 28, 2020 3:28:05 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting American Gods: The Tenth Anniver: Could not find aax file checksum:C:\***\OpenAudible\aax\American Gods The Tenth Anniversary Edition (A Full Cast Production).AAX. size=570659229 exists=true
err=
out=
Jun 28, 2020 3:28:05 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting American Gods: The Tenth Anniver: Could not find aax file checksum:C:\***\OpenAudible\aax\American Gods The Tenth Anniversary Edition (A Full Cast Production).AAX. size=570659229 exists=true
err=
out=
Jun 28, 2020 3:28:08 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert
Jun 28, 2020 3:28:08 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert American Gods: The Tenth Anniver In progress:1 queue: 0 threads:
Jun 28, 2020 3:28:08 PM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:American Gods: The Tenth Anniver size:0
Jun 28, 2020 3:28:08 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -i "C:\***\OpenAudible\aax\American Gods The Tenth Anniversary Edition (A Full Cast Production).AAX" 
Jun 28, 2020 3:28:08 PM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:American Gods: The Tenth Anniver
java.io.IOException: Could not find aax file checksum:C:\***\OpenAudible\aax\American Gods The Tenth Anniversary Edition (A Full Cast Production).AAX. size=570659229 exists=true
err=
out=
	at org.openaudible.convert.LookupKey.getFileChecksum(LookupKey.java:86)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:103)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:116)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:382)
	at org.openaudible.convert.ConvertJob.getMp3Args(ConvertJob.java:140)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:245)
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:260)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jun 28, 2020 3:28:08 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert American Gods: The Tenth Anniver
java.io.IOException: Could not find aax file checksum:C:\***\OpenAudible\aax\American Gods The Tenth Anniversary Edition (A Full Cast Production).AAX. size=570659229 exists=true
err=
out=
	at org.openaudible.convert.LookupKey.getFileChecksum(LookupKey.java:86)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:103)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:116)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:382)
	at org.openaudible.convert.ConvertJob.getMp3Args(ConvertJob.java:140)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:245)
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:260)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jun 28, 2020 3:28:08 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:American Gods: The Tenth Anniver remaining queue size:0
Jun 28, 2020 3:28:08 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting American Gods: The Tenth Anniver: Could not find aax file checksum:C:\***\OpenAudible\aax\American Gods The Tenth Anniversary Edition (A Full Cast Production).AAX. size=570659229 exists=true
err=
out=
Jun 28, 2020 3:28:12 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Jun 28, 2020 3:28:13 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:4

```

**Comment by openaudible** [comment]
ffmpeg is required to run on that computer. Are you using Windows N? Try running ffmpeg from the command line and make sure it runs. Check also your firewall/anti-virus. The copy of ffmpeg we use is in Program Files/OpenAudible/bin/win/ffmpeg.exe
