### ISSUE TITLE
Cannot download books for some reason.

### ISSUE THREAD

**Issue by chamunks** [openaudible/openaudible#41]
Console output stashed on hastebin.com so it can self destruct eventually. https://hastebin.com/ovufupewen.js 

This is using the latest version of the software you published a day ago as recommended.  The new update looks great! Works much smoother too.  Very excited to see it.  Hope it can work soon!

**Comment by r3lax** [comment]
I am seeing the same issues on my mac OpenAudbile install.  Lots of book titles recognized, but nothing gets populated after the scan.  Console shows the following error for every title:
WARNING: invalid book: required:product_id missing from <INSERT BOOK TITLE>

**Comment by openaudible** [comment]
What happens when you click on a "download" button when viewing your library from the built-in browser? It should download a file (or open audible Download manager) , and not redirect you to a /howtolisten page. 

If it takes you to the how to listen page, you need to change your settings and toggle the Check for Audible settings.. but it should also have warned you. Something is definitely up, but not too surprised as this version as a lot of changes. 

 Let me know and I can try to come up with a fix. Thanks for the hastebin.

**Comment by chamunks** [comment]
Clicking Download the following is the console output and nothing generally happens.  

```
Oct 07, 2018 8:55:54 PM org.openaudible.desktop.swt.manager.AppLoader <init>
INFO: Starting OpenAudible build 1.2.0 for cocoa swt 4623 jvm 1.8.0_144
Oct 07, 2018 8:55:56 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.2.0
Oct 07, 2018 8:55:57 PM org.openaudible.Audible checkLibrary
INFO: bl=0, gl=0
Oct 07, 2018 8:55:57 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/OpenAudible.app/Contents/java/app/bin/mac_ffmpeg -version 
Oct 07, 2018 8:55:58 PM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-89585-g5533cbf-tessus Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil      56.  6.100 / 56.  6.100
libavcodec     58.  8.100 / 58.  8.100
libavformat    58.  3.100 / 58.  3.100
libavdevice    58.  0.100 / 58.  0.100
libavfilter     7.  7.100 /  7.  7.100
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100

Oct 07, 2018 8:56:02 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: http://openaudible.org/swt_version.json?platform=mac&version=1.2.0
Oct 07, 2018 8:56:16 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Oct 07, 2018 8:56:16 PM org.openaudible.desktop.swt.manager.AudibleGUI connectTask
INFO: connectTask:https://www.audible.com/lib
Oct 07, 2018 8:56:17 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: https://www.audible.com/lib
Oct 07, 2018 8:56:17 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient getPage
INFO: BrowserClient getPage:https://www.audible.com/lib js=true
Oct 07, 2018 8:56:17 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: https://www.audible.com/lib
Oct 07, 2018 8:56:17 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient getPage
INFO: BrowserClient getPage:https://www.audible.com/lib js=true
Oct 07, 2018 8:56:18 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser audiblePageVisited
INFO: audiblePageVisited:https://www.audible.com/lib connected:false
Oct 07, 2018 8:56:18 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser audiblePageVisited
INFO: audiblePageVisited:https://www.audible.com/lib connected:false
Oct 07, 2018 8:56:21 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient$1 task
SEVERE: error getPage:https://www.audible.com/lib
java.lang.NullPointerException
	at org.eclipse.swt.browser.WebKit.webView_didFailProvisionalLoadWithError_forFrame(Unknown Source)
	at org.eclipse.swt.browser.WebKit.browserProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.applicationProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.waitForCallback(BrowserWebClient.java:101)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.access$000(BrowserWebClient.java:22)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient$1.task(BrowserWebClient.java:72)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:184)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:121)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:99)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.getPage(BrowserWebClient.java:64)
	at org.openaudible.audible.AudibleClient.getPage(AudibleClient.java:151)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.setUrl(AudibleBrowser.java:497)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.<init>(AudibleBrowser.java:86)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.newBrowserWindow(AudibleBrowser.java:147)
	at org.openaudible.desktop.swt.manager.AudibleGUI.lambda$createBrowser$4(AudibleGUI.java:1172)
	at org.openaudible.desktop.swt.gui.SWTAsync$2.task(SWTAsync.java:170)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:184)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.waitForCallback(BrowserWebClient.java:101)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.access$000(BrowserWebClient.java:22)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient$1.task(BrowserWebClient.java:72)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:184)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:121)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:99)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.getPage(BrowserWebClient.java:64)
	at org.openaudible.audible.AudibleClient.getPage(AudibleClient.java:151)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.setUrl(AudibleBrowser.java:497)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.<init>(AudibleBrowser.java:86)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.newBrowserWindow(AudibleBrowser.java:147)
	at org.openaudible.desktop.swt.manager.AudibleGUI.lambda$createBrowser$4(AudibleGUI.java:1172)
	at org.openaudible.desktop.swt.gui.SWTAsync$2.task(SWTAsync.java:170)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:184)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:121)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:99)
	at org.openaudible.desktop.swt.gui.SWTAsync.block2(SWTAsync.java:173)
	at org.openaudible.desktop.swt.manager.AudibleGUI.createBrowser(AudibleGUI.java:1171)
	at org.openaudible.desktop.swt.manager.AudibleGUI$7.task(AudibleGUI.java:1213)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:184)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:158)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:326)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:495)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.runTask(ProgressDialog.java:327)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog$1.task(ProgressDialog.java:139)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:184)
	at org.openaudible.desktop.swt.gui.SWTAsync.slow(SWTAsync.java:136)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.doProgressTask(ProgressDialog.java:128)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.doProgressTask(ProgressDialog.java:124)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:254)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:250)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:65)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:311)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:339)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:435)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:54)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:62)
	at org.openaudible.desktop.Application.main(Application.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)

Oct 07, 2018 8:56:21 PM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:'Download Audiobooks with Audible.com' https://www.audible.com/lib
Oct 07, 2018 8:56:21 PM org.openaudible.audible.AudibleScraper setLoggedIn
INFO: Setting logged in to true page=Download Audiobooks with Audible.com
Oct 07, 2018 8:56:31 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Browser
Oct 07, 2018 8:56:45 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
```

**Comment by openaudible** [comment]
Nasty. OSX webkit code. Will take a look.

**Comment by openaudible** [comment]
Unable to reproduce on my OS X system. Don't have any statistics on which systems are affected... can't tell if this is a one off event or if its happening. Will add some additional logging for next release.

**Comment by ryantstone** [comment]
Mine was on Mojave (whichever the current stable build is) Mid-2015 MBP

**Comment by Leopere** [comment]
Yup this doesn't work on Linux either. Ubuntu 18.04 Desktop with the latest updates running the latest version.
