### ISSUE TITLE
Cannot find checksum when converting from aax

### ISSUE THREAD

**Issue by jpurtle80** [openaudible/openaudible#412]
When trying to convert from aax to mp3 on mac it states "could not find aax file checksum:..."

**Comment by jpurtle80** [comment]
went back to version 2.1.1 and it is now converting.

**Comment by RustArea** [comment]
I'm having the same problem. Where do you find a download for version 2.1.1?

**Comment by jpurtle80** [comment]
Luckily I still had the driver on my desktop (Mac) for version 2.1.1, so I
just reinstalled it.

**Comment by openaudible** [comment]
Can you try this version for older macs:
If I can confirm it works I'll replace or upgrade the download:
http://openaudible.org/prerelease/OpenAudible_2.2_mac.dmg

This is from issue #405. 
If you're not on a Mac, or it still doesn't work, kindly copy and paste the output from the OpenAudible Console Window where the error occurs.
Thanks!

**Comment by jpurtle80** [comment]
@openaudible I actually tried that before I posted an issue on here as I saw it on issue #405.  Unfortunately
it didn't work either.

**Comment by openaudible** [comment]
Ok. I need the log file to see what's going on. 

You can also run the "ffmpeg" command line from "Terminal.app" as well to make sure your copy of ffmpeg (recently upgraded to be LGPL compliant).. 

Just open the File: Console and copy and paste anything after you see after you attempt a convert.

**Comment by thegoodsheppard** [comment]
`Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0`

I believe this is it but here are all of the log lines for a failed conversion:

```tesx
Jul 02, 2020 8:32:33 AM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Frederick Douglass: Prophet of F: Could not find aax file checksum:/Volumes/Pegasus/OpenAudible/aax/Frederick Douglass Prophet of Freedom.AAX. size=1075582931 exists=true
err=dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg
  Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

out=
Jul 02, 2020 8:32:37 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert
Jul 02, 2020 8:32:37 AM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert Frederick Douglass: Prophet of F In progress:1 queue: 0 threads:
Jul 02, 2020 8:32:37 AM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:Frederick Douglass: Prophet of F size:0
Jul 02, 2020 8:32:37 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -i "/Volumes/Pegasus/OpenAudible/aax/Frederick Douglass Prophet of Freedom.AAX" 
Jul 02, 2020 8:32:37 AM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:Frederick Douglass: Prophet of F
java.io.IOException: Could not find aax file checksum:/Volumes/Pegasus/OpenAudible/aax/Frederick Douglass Prophet of Freedom.AAX. size=1075582931 exists=true
err=dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg
  Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

out=
	at org.openaudible.convert.LookupKey.getFileChecksum(LookupKey.java:86)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:103)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:116)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:382)
	at org.openaudible.convert.ConvertJob.getMp3Args(ConvertJob.java:140)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:245)
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:260)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jul 02, 2020 8:32:37 AM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Frederick Douglass: Prophet of F
java.io.IOException: Could not find aax file checksum:/Volumes/Pegasus/OpenAudible/aax/Frederick Douglass Prophet of Freedom.AAX. size=1075582931 exists=true
err=dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg
  Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

out=
	at org.openaudible.convert.LookupKey.getFileChecksum(LookupKey.java:86)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:103)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:116)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:382)
	at org.openaudible.convert.ConvertJob.getMp3Args(ConvertJob.java:140)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:245)
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:260)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jul 02, 2020 8:32:37 AM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Frederick Douglass: Prophet of F remaining queue size:0
Jul 02, 2020 8:32:37 AM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Frederick Douglass: Prophet of F: Could not find aax file checksum:/Volumes/Pegasus/OpenAudible/aax/Frederick Douglass Prophet of Freedom.AAX. size=1075582931 exists=true
err=dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg
  Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

out=
Jul 02, 2020 8:32:42 AM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:18
```

**Comment by openaudible** [comment]
Can you try this release:
https://openaudible.org/prerelease/OpenAudible_2.2_mac.dmg

**Comment by jocama** [comment]
With the release posted above on a 2014 Macbook Pro with OS X 10.11.6, I get the following log:

```
INFO: create MP3 /Users/jmaughon/Library/OpenAudible/aax/Treasure Island An Audible Original Drama.AAX result:133
Jul 05, 2020 6:54:11 PM org.openaudible.convert.ConvertJob doConversion
SEVERE: conversion got non-zero result:133 
stdErr:ider specifying a lower framerate, a different muxer or -vsync 2, ...dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin,   Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg,   Expected in: /usr/lib/libSystem.B.dylib, , dyld: Symbol not found: ____chkstk_darwin,   Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg,   Expected in: /usr/lib/libSystem.B.dylib, 
Jul 05, 2020 6:54:11 PM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:Treasure Island: An Audible Orig
java.io.IOException: Failed to convert /Users/jmaughon/Library/OpenAudible/aax/Treasure Island An Audible Original Drama.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jul 05, 2020 6:54:11 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Treasure Island: An Audible Orig
java.io.IOException: Failed to convert /Users/jmaughon/Library/OpenAudible/aax/Treasure Island An Audible Original Drama.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jul 05, 2020 6:54:11 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Treasure Island: An Audible Orig remaining queue size:0
Jul 05, 2020 6:54:11 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Treasure Island: An Audible Orig: Failed to convert /Users/jmaughon/Library/OpenAudible/aax/Treasure Island An Audible Original Drama.AAX. Check console for details.
Jul 05, 2020 6:54:16 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation

**Comment by openaudible** [comment]
New version to try:
https://openaudible.org/prerelease/OpenAudible_2.2_mac.dmg
Thanks!

**Comment by tomsem** [comment]
I had this issue, and the new version ^^ fixed it.

**Comment by AlexEldrige** [comment]
Yep, this fixed it, thanks so much.

**Comment by Ang7753** [comment]
I am having this same issue with Win version 2.2.

**Comment by openaudible** [comment]
Yes. AAXC is definitely not supported. You should be able to download any books you own as AAX. (Podcasts and unlimited access books are not convertable.)
