### ISSUE TITLE
--activation_bytes <not found>

### ISSUE THREAD

**Issue by m-cat** [openaudible/openaudible#432]
Looks like OA 2.3.2 is passing the above argument to ffmpeg causing the conversion to fail. Switched from 2.3.2 to 2.2 as linked [here](https://github.com/openaudible/openaudible/issues/405#issuecomment-654341796) and the old version works. On OSX.

**Comment by openaudible** [comment]
OK. That is a Mac only bug. Fixing that. Thank you.

**Comment by openaudible** [comment]
Can you try this version?
https://openaudible.org/prerelease

**Comment by m-cat** [comment]
Thanks, unfortunately I still see the same issue. Here's the relevant log:

```
INFO: MessageDialog: title:Proceed? body:Automatic conversions are enabled. Start 1 conversions(s) now? response:BUTTON_YES
Aug 20, 2020 8:24:09 AM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert Healing Trauma: Restoring the Wi In progress:1 queue: 0 threads:
Aug 20, 2020 8:24:09 AM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:Healing Trauma: Restoring the Wi size:0
Aug 20, 2020 8:24:09 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/rcrack /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_9_10000x791022_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_3_10000x792120_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_6_10000x791458_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_4_10000x790743_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_5_10000x790568_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_0_10000x789935_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_8_10000x790202_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_2_10000x790991_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_1_10000x791425_0.rtc /Applications/OpenAudible.app/Contents/Resources/app/bin/tables/audible_byte#4-4_7_10000x791707_0.rtc -h de0fa5f27dfa1ce7eb311253857169c347625bda 
Aug 20, 2020 8:24:09 AM org.openaudible.convert.LookupKey _lookupKey
INFO: audible_byte#4-4_0_10000x789935_0.rtc:
audible_byte#4-4_0_10000x789935_0.rtc is not a rainbow table

audible_byte#4-4_1_10000x791425_0.rtc:
audible_byte#4-4_1_10000x791425_0.rtc is not a rainbow table

audible_byte#4-4_2_10000x790991_0.rtc:
audible_byte#4-4_2_10000x790991_0.rtc is not a rainbow table

audible_byte#4-4_3_10000x792120_0.rtc:
audible_byte#4-4_3_10000x792120_0.rtc is not a rainbow table

audible_byte#4-4_4_10000x790743_0.rtc:
audible_byte#4-4_4_10000x790743_0.rtc is not a rainbow table

audible_byte#4-4_5_10000x790568_0.rtc:
audible_byte#4-4_5_10000x790568_0.rtc is not a rainbow table

audible_byte#4-4_6_10000x791458_0.rtc:
audible_byte#4-4_6_10000x791458_0.rtc is not a rainbow table

audible_byte#4-4_7_10000x791707_0.rtc:
audible_byte#4-4_7_10000x791707_0.rtc is not a rainbow table

audible_byte#4-4_8_10000x790202_0.rtc:
audible_byte#4-4_8_10000x790202_0.rtc is not a rainbow table

audible_byte#4-4_9_10000x791022_0.rtc:
audible_byte#4-4_9_10000x791022_0.rtc is not a rainbow table

statistics
-------------------------------------------------------
plaintext found:          0 of 1 (0.00%)
total disk access time:   0.00 s
total cryptanalysis time: 0.00 s
total chain walk step:    0
total false alarm:        0
total chain walk step due to false alarm: 0

result
-------------------------------------------------------
de0fa5f27dfa1ce7eb311253857169c347625bda  <notfound>  hex:<notfound>

Aug 20, 2020 8:24:09 AM org.openaudible.convert.LookupKey lookupKey
INFO: <notfound>
Aug 20, 2020 8:24:09 AM org.openaudible.convert.ConvertJob doConversion
INFO: converting: Healing Trauma: Restoring the Wi to temp file: /Users/marcin/Library/OpenAudible/tmp/asin_B002V5BMPE_temp.mp3 from source /Users/marcin/Library/OpenAudible/aax/Healing Trauma Restoring the Wisdom of the Body.AAX length=199747234
Aug 20, 2020 8:24:09 AM org.openaudible.convert.ConvertJob doConversion
INFO: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -activation_bytes <notfound> -i "/Users/marcin/Library/OpenAudible/aax/Healing Trauma Restoring the Wisdom of the Body.AAX" -map_metadata 0 -metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 -metadata product_id=SP_TRUE_000107 -metadata asin=B002V5BMPE -metadata "narrated_by=Peter A. Levine" -metadata "book_genre=Health & Wellness:Alternative & Complementary Medicine" -metadata major_brand= -metadata minor_version= -metadata compatible_brands= -metadata "title=Healing Trauma: Restoring the Wisdom of the Body" -metadata "author=Peter A. Levine" -metadata year=2010-08-30 -metadata "comment=On Healing Trauma, respected therapist and teacher Peter A. Levine brings you face to face with his effective new treatment - not a talking cure..." -metadata json64=eyJzdW1tYXJ5IjoiQXJlIHlvdSBleHBlcmllbmNpbmcgcGh5c2ljYWwgb3IgZW1vdGlvbmFsIHN5bXB0b21zIHRoYXQgbm8gb25lIGlzIGFibGUgdG8gZXhwbGFpbj8gSWYgc28sIHlvdSBtYXkgYmUgc3VmZmVyaW5nIGEgdHJhdW1hdGljIHJlYWN0aW9uIHRvIGEgcGFzdCBldmVudCwgdGVhY2hlcyBMZXZpbmUuIiwicmF0aW5nX2F2ZXJhZ2UiOiI0LjU3NzA0OTE4MDMyNzg2OSIsImNvcHlyaWdodCI6IsKpMTk5OSBQZXRlciBMZXZpbmUgKFApMTk5OSBTb3VuZHMgVHJ1ZSIsImF1dGhvciI6IlBldGVyIEEuIExldmluZSIsImRlc2NyaXB0aW9uIjoiT24gSGVhbGluZyBUcmF1bWEsIHJlc3BlY3RlZCB0aGVyYXBpc3QgYW5kIHRlYWNoZXIgUGV0ZXIgQS4gTGV2aW5lIGJyaW5ncyB5b3UgZmFjZSB0byBmYWNlIHdpdGggaGlzIGVmZmVjdGl2ZSBuZXcgdHJlYXRtZW50IC0gbm90IGEgXCJ0YWxraW5nXCIgY3VyZS4uLiIsImxhbmd1YWdlIjoiZW5nbGlzaCIsInRpdGxlIjoiSGVhbGluZyBUcmF1bWE6IFJlc3RvcmluZyB0aGUgV2lzZG9tIG9mIHRoZSBCb2R5IiwidGl0bGVfc2hvcnQiOiJIZWFsaW5nIFRyYXVtYTogUmVzdG9yaW5nIHRoZSBXaXNkb20gb2YgdGhlIEJvZHkiLCJpbmZvX2xpbmsiOiJodHRwczovL3d3dy5hdWRpYmxlLmNvbS9wZC9IZWFsaW5nLVRyYXVtYS1BdWRpb2Jvb2svQjAwMlY1Qk1QRSIsInJhdGluZ19jb3VudCI6IjMwNSIsImR1cmF0aW9uIjoiMDY6NTI6NDMiLCJmaWxlbmFtZSI6IkhlYWxpbmcgVHJhdW1hIFJlc3RvcmluZyB0aGUgV2lzZG9tIG9mIHRoZSBCb2R5IiwibmFycmF0ZWRfYnkiOiJQZXRlciBBLiBMZXZpbmUiLCJyZWxlYXNlX2RhdGUiOiIzMC1BVUctMjAxMCIsInByb2R1Y3RfaWQiOiJTUF9UUlVFXzAwMDEwNyIsImdlbnJlIjoiSGVhbHRoICYgV2VsbG5lc3M6QWx0ZXJuYXRpdmUgJiBDb21wbGVtZW50YXJ5IE1lZGljaW5lIiwicHVibGlzaGVyIjoiU291bmRzIFRydWUiLCJhc2luIjoiQjAwMlY1Qk1QRSJ9 /Users/marcin/Library/OpenAudible/tmp/asin_B002V5BMPE_temp.mp3 
Aug 20, 2020 8:24:09 AM org.openaudible.convert.ConvertJob doConversion
INFO: create MP3 /Users/marcin/Library/OpenAudible/aax/Healing Trauma Restoring the Wisdom of the Body.AAX result:1
Aug 20, 2020 8:24:09 AM org.openaudible.convert.ConvertJob doConversion
SEVERE: conversion got non-zero result:1 
stdErr:ffmpeg version N-98470-g7772666e5b-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers,   built with Apple clang version 11.0.0 (clang-1100.0.33.17),   configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-libmp3lame --pkg-config-flags=--static --disable-securetransport --disable-ffplay,   libavutil      56. 55.100 / 56. 55.100,   libavcodec     58. 95.100 / 58. 95.100,   libavformat    58. 48.100 / 58. 48.100,   libavdevice    58. 11.101 / 58. 11.101,   libavfilter     7. 87.100 /  7. 87.100,   libswscale      5.  8.100 /  5.  8.100,   libswresample   3.  8.100 /  3.  8.100, [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7ff8f9504e00] Error setting option activation_bytes to value <notfound>., /Users/marcin/Library/OpenAudible/aax/Healing Trauma Restoring the Wisdom of the Body.AAX: Invalid argument
Aug 20, 2020 8:24:09 AM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:Healing Trauma: Restoring the Wi
java.io.IOException: Failed to convert /Users/marcin/Library/OpenAudible/aax/Healing Trauma Restoring the Wisdom of the Body.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:400)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:452)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Aug 20, 2020 8:24:09 AM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Healing Trauma: Restoring the Wi
java.io.IOException: Failed to convert /Users/marcin/Library/OpenAudible/aax/Healing Trauma Restoring the Wisdom of the Body.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:400)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:452)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Aug 20, 2020 8:24:09 AM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Healing Trauma: Restoring the Wi remaining queue size:0
Aug 20, 2020 8:24:09 AM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Healing Trauma: Restoring the Wi: Failed to convert /Users/marcin/Library/OpenAudible/aax/Healing Trauma Restoring the Wisdom of the Body.AAX. Check console for details.
Aug 20, 2020 8:24:09 AM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Healing Trauma: Restoring the Wi: Failed to convert /Users/marcin/Library/OpenAudible/aax/Healing Trauma Restoring the Wisdom of the Body.AAX. Check console for details.
Aug 20, 2020 8:24:39 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
```

**Comment by openaudible** [comment]
Ok. We fixed that in a prerelease:
https://openaudible.org/prerelease
An a full version will be updated soon.

**Comment by openaudible** [comment]
OK. Try the 2.3.4 version. If it doesn't work, please submit a bug report from the About menu and reference #432. 
https://openaudible.org/

**Comment by m-cat** [comment]
It works, thank you!!
