### ISSUE TITLE
NullPointerException on OSX 10.15.7 Catalina

### ISSUE THREAD

**Issue by mbonaci** [openaudible/openaudible#509]
App was built, packaged and started from the command line.
The following exception happens immediately after starting the app and on almost every action inside the app.
Here's an example for `Connect to Audible` (after starting the in-app browser and logging in):
```
Dec 16, 2020 11:22:49 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Unhandled event loop exception during blocked modal context.
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:158)
        at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:326)
        at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:495)
        at org.openaudible.desktop.swt.gui.progress.ProgressDialog.runTask(ProgressDialog.java:328)
        at org.openaudible.desktop.swt.gui.progress.ProgressDialog$1.task(ProgressDialog.java:138)
        at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:184)
        at org.openaudible.desktop.swt.gui.SWTAsync.slow(SWTAsync.java:136)
        at org.openaudible.desktop.swt.gui.progress.ProgressDialog.doProgressTask(ProgressDialog.java:127)
        at org.openaudible.desktop.swt.gui.progress.ProgressDialog.doProgressTask(ProgressDialog.java:123)
        at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:309)
        at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:251)
        at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:66)
        at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:311)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:332)
        at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:428)
        at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:54)
        at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:62)
        at org.openaudible.desktop.Application.main(Application.java:19)
Caused by: java.lang.NullPointerException
        at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
        at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
        at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
        at org.eclipse.jface.dialogs.Dialog.shortenText(Dialog.java:348)
        at org.eclipse.jface.dialogs.ProgressMonitorDialog.setMessage(ProgressMonitorDialog.java:638)
        at org.eclipse.jface.dialogs.ProgressMonitorDialog.access$3(ProgressMonitorDialog.java:630)
        at org.eclipse.jface.dialogs.ProgressMonitorDialog$ProgressMonitor.beginTask(ProgressMonitorDialog.java:180)
        at org.eclipse.jface.operation.AccumulatingProgressMonitor$1.run(AccumulatingProgressMonitor.java:126)
        at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
        ... 30 more
Dec 16, 2020 11:22:49 PM org.openaudible.desktop.swt.gui.progress.ProgressDialog runTask
SEVERE: java.lang.reflect.InvocationTargetException
```

**Comment by openaudible** [comment]
It looks like a bug that has been reported and possibly fixed [https://bugs.eclipse.org/bugs/show_bug.cgi?id=548961] 

I don't think it effects many people as this might be the first report.

I'll update the UI code to the latest version in the next release (and beta, that we're working on) and post a message here.

**Comment by openaudible** [comment]
Feel free to try the beta. We updated the UI code we use to the latest available. 
https://openaudible.org/beta
If that doesn't fix it, there may be something incompatible on your system that we can't fix.
