### ISSUE TITLE
Unable to Sync.

### ISSUE THREAD

**Issue by acr1161** [openaudible/openaudible#523]
Recently, I've been unable to Sync open audible.  I connect to audible, and a window opens to show my library.  But when I try to perform a Quick Sync or Full Sync, the process appears to start, but then I get "Unable to Connect" Try connecting in web browser...
Any assistance would be appreciated.
![image](https://user-images.githubusercontent.com/77207749/104105919-941cf680-5266-11eb-9e47-eb48a2a2e1f7.png)

**Comment by openaudible** [comment]
What happens when you open the OpenAudible web browser? And go to https://audible.com/lib
?
You can also try the beta version of OpenAudible which has support for a new type of library download:
https://openaudible.org/beta

**Comment by alkenes** [comment]
I'm also receiving this error. It keeps timing out when trying to reach audible.com/lib has that url always redirected to https://www.audible.com/library/titles or is that a change that broke this? If I navigate to the /lib page in a browser (integrated or native) I get redirected fine. Console output below.

```
java.lang.Exception: Timeout waiting for page
	at org.openaudible.desktop.swt.manager.browser.GetPageTask.waitForPageLoad(GetPageTask.java:173)
	at org.openaudible.desktop.swt.manager.browser.GetPageTask.getPage(GetPageTask.java:123)
	at org.openaudible.desktop.swt.manager.browser.GetPageTask.task(GetPageTask.java:84)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:252)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:142)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:119)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.getPage(BrowserWebClient.java:116)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.getPage(BrowserWebClient.java:95)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.setUrl(AudibleBrowser.java:445)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.setUrl(AudibleBrowser.java:429)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.lambda$show$4(AudibleBrowser.java:333)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:416)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:516)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:102)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:112)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

Jan 11, 2021 2:40:00 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
SEVERE: 02:38:59.903	06:00:00.000	waitForPageLoad:start
02:39:00.461	06:00:00.558	browser state unknown -> loading
02:39:07.814	06:00:07.911	event:LocChanged -> LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/library/titles top=true doit=false}
02:39:08.067	06:00:08.164	browser state loading -> complete
02:40:00.336	06:01:00.433	Warning.. timeout waiting for page load
Jan 11, 2021 2:40:00 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 487 to disk:C:\Users\me\OpenAudible\tmp\0.txt
Jan 11, 2021 2:42:16 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
```

**Comment by openaudible** [comment]
Disable pi-hole if you have it. Otherwise... 
Can you try the beta version?

**Comment by alkenes** [comment]
Pi hole was the problem for me. Do you happen to know what domains are being blocked so I can whitelist them?

**Comment by acr1161** [comment]
BIG FACE PALM!  🤦‍♂️ I should have know to do that…  I feel like an idiot…

 

Thanks for the common sense…

 

Allan Roberts

**Comment by openaudible** [comment]
Ok. Closing as known issue.
