### ISSUE TITLE
Author Hyperlink Misloads for Some Audible Books

### ISSUE THREAD

**Issue by 1234shai** [openaudible/openaudible#589]
I've noticed that the Author hyperlink misloads for hyperlinks belonging to some Audible books.  For example, Benjamin Wiker https://www.audible.com/pd/B003RCTOTQ loads instead to here: https://www.audible.com/author/Flannery-OConnor/B000APYI6W.  I don't know why - it doesn't seem to occur with most of they hyperlinks.  

Here was what appeared in the code: 

Mar 14, 2021 6:24:42 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
SEVERE: 0:getPage:https://www.audible.com/author/Flannery-OConnor/B000APYI6W error java.lang.Exception: Timeout waiting for page60076 ms
06:23:42.203	02:00:00.001	waitForPageLoad:start
06:23:42.714	02:00:00.512	browser state unknown -> loading
06:23:43.400	02:00:01.198	event:LocChanged -> LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/author/Flannery-OConnor/B000APYI6W top=true doit=false}
06:23:43.782	02:00:01.580	browser state loading -> complete
06:24:42.278	02:01:00.076	Warning.. timeout waiting for page load. state=complete inspect=ProgChanged=5,ProgComplete=0,LocChanging=0,LocChanged=1,;same=0;diff=0;url=https://www.audible.com/author/Flannery-OConnor/B000APYI6W
Check that no ad-blockers like pi-hole are used. 
java.lang.Exception: Timeout waiting for page
	at org.openaudible.desktop.swt.manager.browser.GetPageTask.waitForPageLoad(GetPageTask.java:171)
	at org.openaudible.desktop.swt.manager.browser.GetPageTask.getPage(GetPageTask.java:120)
	at org.openaudible.desktop.swt.manager.browser.GetPageTask.task(GetPageTask.java:81)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:252)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:143)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:120)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.getPage(BrowserWebClient.java:108)
	at org.openaudible.desktop.swt.manager.browser.BrowserWebClient.getPage(BrowserWebClient.java:87)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.setUrl(AudibleBrowser.java:440)
	at org.openaudible.desktop.swt.manager.browser.AudibleBrowser.setUrl(AudibleBrowser.java:423)
	at org.openaudible.desktop.swt.manager.AudibleGUI$11.task(AudibleGUI.java:1733)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:252)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:143)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:120)
	at org.openaudible.desktop.swt.manager.AudibleGUI.browse(AudibleGUI.java:1726)
	at org.openaudible.desktop.swt.manager.AudibleGUI.browse(AudibleGUI.java:1677)
	at org.openaudible.desktop.swt.manager.views.BookInfoPanel.linkClicked(BookInfoPanel.java:247)
	at org.openaudible.desktop.swt.manager.views.BookInfoPanel$1.mouseUp(BookInfoPanel.java:182)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:417)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:517)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:103)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:113)
	at org.openaudible.desktop.Application.main(Application.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Comment by openaudible** [comment]
I think this is just bad data from audible. Nothing we can do about it.
