### ISSUE TITLE
OpenAudible not installing properly on 18.04

### ISSUE THREAD

**Issue by livtin** [openaudible/openaudible#6]
**Error on intallation**
<pre>Starting Installer ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.install4j.runtime.installer.frontend.GUIHelper (file:/home/tina/Downloads/OpenAudible_unix_1_0.sh.20616.dir/i4jruntime.jar) to field sun.awt.X11GraphicsDevice.scale
WARNING: Please consider reporting this to the maintainers of com.install4j.runtime.installer.frontend.GUIHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
</pre>

**The installer starts then this error on start-up**
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Decorations.setImages(Unknown Source)
	at org.openaudible.desktop.swt.manager.Application.initComponents(Application.java:65)
	at org.openaudible.desktop.swt.gui.GUI.startUp(GUI.java:172)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:56)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:28)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:67)
	at org.openaudible.desktop.Application.main(Application.java:8)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)

**Comment by openaudible** [comment]
We are setting the shell image at that point. I have disabled that code the next release, 1.1. Re open if not fixed. Could be the JDK is too new (we only test with 8.).
