### ISSUE TITLE
What is this about?

### ISSUE THREAD

**Issue by Sainrival** [openaudible/openaudible#704]
java.lang.IllegalStateException: assertNotGUI failed
	at org.openaudible.desktop.swt.gui.SWTAsync.assertNot(SWTAsync.java:110)
	at org.openaudible.bookfiles.BookFiles.forceUpdate(BookFiles.java:264)
	at org.openaudible.Audible.findOrphanedFiles(Audible.java:789)
	at org.openaudible.desktop.swt.manager.AudibleGUI.checkOrphansGUI(AudibleGUI.java:282)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshFiles(AudibleGUI.java:1837)
	at org.openaudible.desktop.swt.manager.HintManager.checkHints(HintManager.java:39)
	at org.openaudible.desktop.swt.manager.HintManager.applicationStarted(HintManager.java:29)
	at org.openaudible.desktop.swt.manager.AudibleGUI.applicationStarted(AudibleGUI.java:1560)
	at org.openaudible.desktop.swt.manager.Application.applicationStarted(Application.java:82)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:503)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:101)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:111)
	at org.openaudible.desktop.Application.main(Application.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Comment by littleblackdog77** [comment]
this should be fixed in v3.1.1 on the web site. download it and try it.

**Comment by openaudible** [comment]
Correct. Nasty bug fixed in 3.1.1. Sorry for the inconvenience.

**Comment by Sainrival** [comment]
I upgraded and it’s working again.

Thank you.

 

Marc-Eddy
