### ISSUE TITLE
Error starting OpenAudible 3.1

### ISSUE THREAD

**Issue by littleblackdog77** [openaudible/openaudible#705]
Hi, im getting this error whenever I try to start OpenAudible 3.1 on Windows 10.

Any ideas? Thanks!

java.lang.IllegalStateException: assertNotGUI failed
	at org.openaudible.desktop.swt.gui.SWTAsync.assertNot(SWTAsync.java:110)
	at org.openaudible.bookfiles.BookFiles.forceUpdate(BookFiles.java:264)
	at org.openaudible.Audible.findOrphanedFiles(Audible.java:789)
	at org.openaudible.desktop.swt.manager.AudibleGUI.checkOrphansGUI(AudibleGUI.java:282)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshFiles(AudibleGUI.java:1837)
	at org.openaudible.desktop.swt.manager.HintManager.checkHints(HintManager.java:39)
	at org.openaudible.desktop.swt.manager.HintManager.applicationStarted(HintManager.java:29)
	at org.openaudible.desktop.swt.manager.AudibleGUI.applicationStarted(AudibleGUI.java:1560)
	at org.openaudible.desktop.swt.manager.Application.applicationStarted(Application.java:82)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:503)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:101)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:111)
	at org.openaudible.desktop.Application.main(Application.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Comment by grahameg61** [comment]
Am getting same error after just upgrading to 3.1.   Running Win 10 Build 19043.1165.  Any help greatly appreciated  :)

**Comment by openaudible** [comment]
Fixed in 3.1.1.
Thank you so much for the quick report.

**Comment by grahameg61** [comment]
Awesome - where can I download 3.1.1    ??

**Comment by littleblackdog77** [comment]
I just uninstalled 3.1 and installed 3.1.1 and the same problem. Windows 10 home 19042.1165

java.lang.IllegalStateException: assertNotGUI failed
	at org.openaudible.desktop.swt.gui.SWTAsync.assertNot(SWTAsync.java:110)
	at org.openaudible.bookfiles.BookFiles._updateFileCache(BookFiles.java:128)
	at org.openaudible.bookfiles.BookFiles.forceUpdate(BookFiles.java:267)
	at org.openaudible.Audible.findOrphanedFiles(Audible.java:789)
	at org.openaudible.desktop.swt.manager.AudibleGUI.checkOrphansGUI(AudibleGUI.java:282)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshFiles(AudibleGUI.java:1837)
	at org.openaudible.desktop.swt.manager.HintManager.checkHints(HintManager.java:39)
	at org.openaudible.desktop.swt.manager.HintManager.applicationStarted(HintManager.java:29)
	at org.openaudible.desktop.swt.manager.AudibleGUI.applicationStarted(AudibleGUI.java:1560)
	at org.openaudible.desktop.swt.manager.Application.applicationStarted(Application.java:82)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:503)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:101)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:111)
	at org.openaudible.desktop.Application.main(Application.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Comment by openaudible** [comment]
Ok. Going to delete 3.1.1 and figure out what's going on. Will release a new 3.1.1.

**Comment by openaudible** [comment]
that is annoying. Can you try 3.1.1 again? Was able to reproduce and fix...

**Comment by littleblackdog77** [comment]
Hi, it fired up and connected to audible so all fixed I think :)

**Comment by littleblackdog77** [comment]
its working fine now, thanks a lot!

**Comment by openaudible** [comment]
Great. 

Seemed to only affect new libraries so didn’t affect me or the beta users. Really appreciate the good bug reports. Will leave open for a day or two in case people wonder why 3.1 isnt working. 

fix is to download and use 3.1.1.

**Comment by grahameg61** [comment]
Works like a charm - thanks for the speedy fix  :)
