### ISSUE TITLE
ffprobe error

### ISSUE THREAD

**Issue by Tie-fighter** [openaudible/openaudible#720]
When trying to convert audiobooks, some work while others report an "ffprobe error"

```
Sep. 20, 2021 11:49:34 VORM. org.openaudible.convert.ConvertJob convert
SEVERE: {
 "exception": "ffprobe error",
 "stacktrace": "java.io.IOException: ffprobe error\r\n\tat org.openaudible.convert.FFProbe.probe(FFProbe.java:52)\r\n\tat org.openaudible.convert.FFProbe.probe(FFProbe.java:22)\r\n\tat org.openaudible.convert.ConvertJob.convert(ConvertJob.java:561)\r\n\tat org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:649)\r\n\tat org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)\r\n",
 "book": {
  "rating_average": "4.774117647058824",
  "chapters": "",
  "description": "<p>Bill, an IT manager at Parts Unlimited, has been tasked with taking on a project critical to the future of the business, code named Phoenix Project....<\/p>",
  "abridged": "false",
  "language": "english",
  "pdf_url": "https://d2fahduf2624mg.cloudfront.net/post_purchase_docs/BK_ACX0_032985/2020-06-22-06-18-10/bk_acx0_032985.pdf",
  "title": "The Phoenix Project - A Novel about IT, DevOps, and Helping Your Business Win 5th Anniversary Edition",
  "info_link": "https://www.audible.de/pd/B00VAZVUD0",
  "duration": "14:46:00",
  "author_link": "https://www.audible.de/author/Gene+Kim/B00AERCJ9E",
  "narrated_by": "Chris Ruen",
  "product_id": "BK_ACX0_032985DE",
  "genre": "Wirtschaft & Karriere:Erfolg im Beruf",
  "summary": "<p>Five years after this sleeper hit took on the world of IT and flipped it on its head, the fifth anniversary edition of <i>The Phoenix Project<\/i> continues to guide IT in the DevOps revolution. In this newly updated and expanded edition of the best-selling <i>The Phoenix Project<\/i>, co-author Gene Kim includes a new afterword and a deeper delve into the Three Ways as described in <i>The DevOps Handbook<\/i>.<\/p> <p>Bill, an IT manager at Parts Unlimited, has been tasked with taking on a project critical to the future of the business, code named Phoenix Project. But the project is massively over budget and behind schedule. The CEO demands Bill must fix the mess in 90 days, or else Bill\u2019s entire department will be outsourced.<\/p> <p>With the help of a prospective board member and his mysterious philosophy of the Three Ways, Bill starts to see that IT work has more in common with manufacturing plant work than he ever imagined. With the clock ticking, Bill must organize work flow, streamline interdepartmental communications, and effectively serve the other business functions at Parts Unlimited.<\/p> <p>In a fast-paced and entertaining style, three luminaries of the DevOps movement deliver a story that anyone who works in IT will recognize. Listeners will not only learn how to improve their own IT organizations, they\u2019ll never view IT the same.<\/p> <p><b>PLEASE NOTE: When you purchase this title, the accompanying PDF will be available in your Audible Library along with the audio.<\/b><\/p>",
  "author": "Gene Kim, Kevin Behr, George Spafford",
  "image_url": "https://m.media-amazon.com/images/I/51Fi5Fq4u5L._SL500_.jpg",
  "title_short": "The Phoenix Project",
  "rating_count": "850",
  "download_link": "",
  "filename": "The Phoenix Project",
  "release_date": "2015-04-07",
  "publisher": "IT Revolution Press",
  "asin": "B00VAZVUD0",
  "purchase_date": "2018-05-20",
  "region": "DE"
 },
 "ffprobe": {}
}
Sep. 20, 2021 11:49:34 VORM. org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert The Phoenix Project item The Phoenix Project
java.io.IOException: ffprobe error
	at org.openaudible.convert.FFProbe.probe(FFProbe.java:52)
	at org.openaudible.convert.FFProbe.probe(FFProbe.java:22)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:561)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:649)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)

Sep. 20, 2021 11:49:34 VORM. org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:The Phoenix Project ConvertQueue working:0 remain:0 success:0 fail:39
Sep. 20, 2021 11:49:34 VORM. org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting The Phoenix Project: ffprobe error
Sep. 20, 2021 11:49:34 VORM. org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting The Phoenix Project: ffprobe error
Sep. 20, 2021 11:49:39 VORM. org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:38
Sep. 20, 2021 11:49:41 VORM. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
```

**Comment by openaudible** [comment]
Strange. A little more error message might have helped. 

Maybe the aax file is damaged? Try selecting book, action show aax, delete or move aax (check the file size and make sure its realistic?) and re-download using openaudible and try to convert.

**Comment by Tie-fighter** [comment]
Redownloading did not help :(

Is there any other logfile/information that I can provide you with?

**Comment by openaudible** [comment]
Sure, quit and relaunch. Select book and action menu Book Report, then try to convert to mp3/m4b. Then send bug report from About menu. Reference issue #720.

**Comment by Tie-fighter** [comment]
Sorry, unable to reproduce anymore.

I deleted the library and web folder, which fixed the issue.
Seems like some metadata was corrupted.
