### ISSUE TITLE
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by gfelbing** [openaudible/openaudible#734]
Download of books that contain characters like umlauts (e.g. ä, ö, etc.) produce an InvalidPathException.
Same for things like à.

Log output (exact book name anonymized):

```
Oct 04, 2021 2:42:14 PM org.openaudible.util.queues.ThreadedQueue jobError
INFORMATION: DownloadQueue error processing Download [...]Café[...]
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: [...]Café[...].AAX.part
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
        at java.base/java.io.File.toPath(File.java:2290)
        at org.openaudible.util.MoveFile.move(MoveFile.java:43)
        at org.openaudible.download.DownloadJob.download(DownloadJob.java:279)
        at org.openaudible.download.DownloadJob.processJob(DownloadJob.java:350)
        at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)
```

**Comment by openaudible** [comment]
Looks like your locale is set wrong.. ? 
Try typing: 
locale
Should be UTF-8 for most items:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
```
There may be a few environment variables I can set in the launcher.. Are you able to run the program using the debug.sh file in OpenAudible application directory? If so, we can experiment with adding some arguments to the command line.

**Comment by gfelbing** [comment]
Hi, I have setup my locales according to https://wiki.archlinux.org/title/locale#Setting_the_locale and enabled 'en_US.UTF8' as well as 'de_DE.UTF8'.
Running locale gives 
```
LANG=C
LC_CTYPE=C
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

Setting the variables mentioned by you in the OpenAudible start script to 'en_US.UTF8' script fixes the download issue.

Regarding your question: Yes, I am able to use the debug.sh and set some variables

**Comment by openaudible** [comment]
OK. Which variables did you change to en_US.UTF8 ? 

A possible fix is to just add "-Dsun.jnu.encoding=utf-8" to the debug.sh script (and keep your locale as "C"). If that works, I can add it to our launchers. 

I just need to be a little careful that I don't break windows or another OS, but I'm pretty sure that's the best fix.

**Comment by gfelbing** [comment]
I just pasted all your proposed variables to the launcher script :)

However, I reverted that change and adjusted the debug script now:

```
#!/bin/bash
# cd to the script's directory.
cd "$(dirname "$0")"

JAVA='jre/bin/java'

# check java version
$JAVA -version

# run OpenAudible from command line.
$JAVA -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.gtk.linux.x86_64-4.6.jar" -Dsun.jnu.encoding=utf-8 -Dfile.encoding=UTF-8 org.openaudible.desktop.Application
```

So I added your proposed parameter and then figured that the debug script uses the OS's java, so I added the $JAVA variable pointed to the packaged jre.

Unfortunately, the classpath seems to be broken:

```
$  ./debug_linux.sh  
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment AdoptOpenJDK (build 12+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12+33, mixed mode)
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/SWT
        at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:41)
        at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:111)
        at org.openaudible.desktop.Application.main(Application.java:41)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.SWT
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
```

**Comment by gfelbing** [comment]
Fun fact, the swt jar set by the script's cp parameter contains a class called SWT:

```
$  jar tf ./org.eclipse.swt.gtk.linux.x86_64.jar | grep SWT
org/eclipse/swt/SWT.class
org/eclipse/swt/SWTError.class
org/eclipse/swt/SWTException.class
org/eclipse/swt/awt/SWT_AWT$1.class
org/eclipse/swt/awt/SWT_AWT.class
org/eclipse/swt/internal/SWTEventListener.class
org/eclipse/swt/internal/SWTMessages.properties
org/eclipse/swt/internal/SWTMessages_ar.properties
org/eclipse/swt/internal/SWTMessages_bg.properties
org/eclipse/swt/internal/SWTMessages_cs.properties
org/eclipse/swt/internal/SWTMessages_da.properties
org/eclipse/swt/internal/SWTMessages_de.properties
org/eclipse/swt/internal/SWTMessages_el.properties
org/eclipse/swt/internal/SWTMessages_en_CA.properties
org/eclipse/swt/internal/SWTMessages_es.properties
org/eclipse/swt/internal/SWTMessages_et.properties
org/eclipse/swt/internal/SWTMessages_eu.properties
org/eclipse/swt/internal/SWTMessages_fa.properties
org/eclipse/swt/internal/SWTMessages_fi.properties
org/eclipse/swt/internal/SWTMessages_fr.properties
org/eclipse/swt/internal/SWTMessages_hi.properties
org/eclipse/swt/internal/SWTMessages_hu.properties
org/eclipse/swt/internal/SWTMessages_id.properties
org/eclipse/swt/internal/SWTMessages_it.properties
org/eclipse/swt/internal/SWTMessages_iw.properties
org/eclipse/swt/internal/SWTMessages_ja.properties
org/eclipse/swt/internal/SWTMessages_ko.properties
org/eclipse/swt/internal/SWTMessages_ku.properties
org/eclipse/swt/internal/SWTMessages_lt.properties
org/eclipse/swt/internal/SWTMessages_lv.properties
org/eclipse/swt/internal/SWTMessages_ml.properties
org/eclipse/swt/internal/SWTMessages_mn.properties
org/eclipse/swt/internal/SWTMessages_nl.properties
org/eclipse/swt/internal/SWTMessages_no.properties
org/eclipse/swt/internal/SWTMessages_pl.properties
org/eclipse/swt/internal/SWTMessages_pt.properties
org/eclipse/swt/internal/SWTMessages_pt_BR.properties
org/eclipse/swt/internal/SWTMessages_ro.properties
org/eclipse/swt/internal/SWTMessages_ru.properties
org/eclipse/swt/internal/SWTMessages_sk.properties
org/eclipse/swt/internal/SWTMessages_sl.properties
org/eclipse/swt/internal/SWTMessages_sr.properties
org/eclipse/swt/internal/SWTMessages_sv.properties
org/eclipse/swt/internal/SWTMessages_th.properties
org/eclipse/swt/internal/SWTMessages_tr.properties
org/eclipse/swt/internal/SWTMessages_uk.properties
org/eclipse/swt/internal/SWTMessages_zh.properties
org/eclipse/swt/internal/SWTMessages_zh_TW.properties
```

**Comment by gfelbing** [comment]
Found the issue. The script references the wrong jar name (the '-4.6' suffix).
After fixing it, I am able to run the debug version using the following script: 

```
#!/bin/bash
# cd to the script's directory.

set -x

cd "$(dirname "$0")"

JAVA='./jre/bin/java'

# check java version
$JAVA -version

# run OpenAudible from command line.
$JAVA -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.gtk.linux.x86_64.jar" -Dsun.jnu.encoding=utf-8 -Dfile.encoding=UTF-8 org.openaudible.desktop.Application
```

**Comment by gfelbing** [comment]
Unfortunately, I get the `java.nio.file.InvalidPathException` again, even with the `-Dsun.jnu.encoding=utf-8 `

**Comment by openaudible** [comment]
Thanks for the updates. Will fix linux debug scripts to remove the version. 

Sounds like sun.jnu.encoding is being set later by looking at the LANG settings.. but "C" should mean UTF-8. 

Instead of ```-Dsun.jnu.encoding=utf-8```
can you try:
```-DLANG=de_DE.UTF8```

I'm curious what is going on.. Do you have a full version (or ISO link) for the archlinux are you using? 
Maybe I can fire up a copy on an a VM.

**Comment by gfelbing** [comment]
The lang parameter did the trick, with this it works.
Regarding my arch version, there is not really a 'version' of arch, just the timestamp of the last update, as it's rolling release.
But IMHO it shouldn't matter, it guess it's even regardless the distro only depending on setting up locales with localectl.

**Comment by openaudible** [comment]
Thank you for the report. Will track it and put up a better error message. Closing!
