### ISSUE TITLE
Could not load SWT library

### ISSUE THREAD

**Issue by Zap4ick** [openaudible/openaudible#780]
Hello.
When I first start the app on Windows I get an error:

java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-win32-4623 in java.library.path: [...] (many paths here)
	no swt-win32 in java.library.path:[...] (many paths here)
	Can't load library: C:\Users\zap4i\swt-win32-4623-64.dll
	Can't load library: C:\Users\zap4i\swt-win32-64.dll

	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:53)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:112)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

I get that I have no library and I've tried to search for it and download but can't find the exact dll files the app asks for. Could you please provide the instruction on where to download it?
Thanks.

**Comment by openaudible** [comment]
OpenAudible requires a 64bit windows. Sounds like you have an old 32 bit PC. Sorry.

**Comment by misterjohnk** [comment]
This happens to me on 64-bit Windows.  This should not be closed.

**Comment by openaudible** [comment]
What version of windows are you using? I have one report that Windows server 2013 is not compatible with our latest upgrade of eclipse SWT library. 

Could you try version 4.3?

https://openaudible.org/versions

**Comment by misterjohnk** [comment]
Windows 7, the last good version.  I can confirm that it broke in 4.4.0, and that it also happens in a VM.  I didn't see anything on the OpenAudible site that Win7 was not supported, or I would not have just paid to upgrade...

**Comment by openaudible** [comment]
Ok. Thanks for that. Will roll it back. Will need to make a new volume slider since that was the widget we used the new library for. Good idea about testing on a VM. Expect a day or two.      ---- On Tue, 06 Aug 2024 16:45:36 -0700  ***@***.******@***.***> wrote ----  
Windows 7, the last good version.  I can confirm that it broke in 4.4.0, and that it also happens in a VM.  I didn't see anything on the OpenAudible site that Win7 was not supported, or I would not have just paid to upgrade...

**Comment by misterjohnk** [comment]
Awesome, thanks!

**Comment by openaudible** [comment]
Try the latest beta: https://openaudible.org/beta 

Let us know! Thanks

**Comment by misterjohnk** [comment]
It works, thanks!  Downloading a book now.
