### ISSUE TITLE
Error Codes - Version 3.5.2

### ISSUE THREAD

**Issue by IamMaris** [openaudible/openaudible#900]
I updated OpenAudible today. It installed without error, but after downloading some new purchases, if I try to view the aax or mp3 from the menu, I get an error menu it cannot open it, yet a window does open and correctly shows the file and/or mp3. The error message and the console error it sends me to is below:

Unable to show file in system explorer. See Console Window (File:Console menu)for more details

***The below is from File:Console menu) ***
WARNING: Non-zero for process:
cmd:"Explorer " /select, "D:\OpenAudible\books\Fugitive Telemetry.mp3" 
error code:1(1)+
stdout:
stderr:
Mar 11, 2022 3:04:54 PM org.openaudible.desktop.swt.gui.GUI reveal
INFO: reveal file error: D:\OpenAudible\books\Fugitive Telemetry.mp3 cmd:"Explorer " /select, "D:\OpenAudible\books\Fugitive Telemetry.mp3" 
error code:1(1)+
stdout:
stderr:
Mar 11, 2022 3:04:54 PM org.openaudible.desktop.swt.gui.GUI reveal
SEVERE: D:\OpenAudible\books\Fugitive Telemetry.mp3
java.lang.Exception: Unable to reveal file in system explorer.
	at org.openaudible.desktop.swt.gui.Reveal.reveal(Reveal.java:292)
	at org.openaudible.desktop.swt.gui.Reveal.lambda$reveal$0(Reveal.java:181)
	at java.base/java.lang.Thread.run(Thread.java:833)

I am using a Samsung Galaxy Book 360+ Windows 11 computer. No error before the update, and as mentioned, it actually does open the window in spite of the error message, but I thought this should be reported as it never happened before.

Maris Whetstone

**Comment by openaudible** [comment]
Please see fix at bottom of issue #899

**Comment by IamMaris** [comment]
That didn't work for me, but as the error popup doesn't prevent me from viewing  aax or mp3 files, I'm not worrying about it. 

Thanks!

**Comment by openaudible** [comment]
Ok. Will  have a fix shortly. Making a bunch of little ease-of-use fixes. Thanks for the report!! Let us know if you find anything else.
