### ISSUE TITLE
After Update to version 3.5.3, get a java error on startup

### ISSUE THREAD

**Issue by Riccardo2017** [openaudible/openaudible#947]
After update from version 3.1 or 3.2 (I am not sure) to the version 3.5.3, Windows 64Bit, I get this message on startup:
"Oh no, error starting application! Check log or stacktrace for details. java.lang.ArrayIndexOutOfBoundsException: Index 515 out of bounds for length 512"

Whats the problem and where can I find the log files to get more details?

Thank you

Riccardo

**Comment by openaudible** [comment]
Hi, that's a new one. We should improve that error message.

If you want, run from the command line:
Start menu, type cmd.exe
then the following:
```
cd C:\Program Files\OpenAudible
.\jre\bin\java -ea -Xmx2048m -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF-8 -jar openaudible_win_x86_64.jar
```
Then copy and paste the error, usually just the last part right before the ArrayIndexOutOfBounds error.

Thanks

**Comment by Riccardo2017** [comment]
Here is the log:

C:\Program Files\OpenAudible>.\jre\bin\java -ea -Xmx2048m -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF-8 -jar openaudible_win_x86_64.jar
Mai 15, 2022 3:22:15 PM org.openaudible.desktop.swt.gui.GUI <init>
INFORMATION: Starting OpenAudible build 3.5.3 for win32 swt 4944 jvm 17.0.1
Mai 15, 2022 3:22:15 PM org.openaudible.Directories getPrefs
INFORMATION: Loading C:\Users\riccardo.XXXXXXX\OpenAudible\settings.json exists=true size=480
Mai 15, 2022 3:22:15 PM org.openaudible.Directories getPrefs
INFORMATION: loaded settings 1636136036265
Mai 15, 2022 3:22:15 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFORMATION: audible desktop 3.5.3 win
Mai 15, 2022 3:22:15 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFORMATION: useHighDPI=false
Mai 15, 2022 3:22:16 PM org.openaudible.desktop.swt.gui.GUI <init>
INFORMATION: Unexpected application error. Check log or stacktrace for details
java.lang.ArrayIndexOutOfBoundsException: Index 515 out of bounds for length 512
        at org.openaudible.desktop.swt.util.shop.PaintShop.buttonPressedImage(PaintShop.java:138)
        at org.openaudible.desktop.swt.layout.GridComposite$ImageButton.<init>(GridComposite.java:530)
        at org.openaudible.desktop.swt.layout.GridComposite.newImageButton(GridComposite.java:579)
        at org.openaudible.desktop.swt.layout.GridComposite.newImageButton(GridComposite.java:584)
        at org.openaudible.desktop.swt.manager.views.MainWindow.createTop(MainWindow.java:92)
        at org.openaudible.desktop.swt.manager.views.MainWindow.<init>(MainWindow.java:46)
        at org.openaudible.desktop.swt.manager.Application.createMainBody(Application.java:46)
        at org.openaudible.desktop.swt.manager.Application.createLayout(Application.java:55)
        at org.openaudible.desktop.swt.manager.Application.initComponents(Application.java:75)
        at org.openaudible.desktop.swt.gui.GUI.startUp(GUI.java:184)
        at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:113)
        at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:138)
        at org.openaudible.desktop.Application.main(Application.java:45)

java.lang.ArrayIndexOutOfBoundsException: Index 515 out of bounds for length 512
        at org.openaudible.desktop.swt.util.shop.PaintShop.buttonPressedImage(PaintShop.java:138)
        at org.openaudible.desktop.swt.layout.GridComposite$ImageButton.<init>(GridComposite.java:530)
        at org.openaudible.desktop.swt.layout.GridComposite.newImageButton(GridComposite.java:579)
        at org.openaudible.desktop.swt.layout.GridComposite.newImageButton(GridComposite.java:584)
        at org.openaudible.desktop.swt.manager.views.MainWindow.createTop(MainWindow.java:92)
        at org.openaudible.desktop.swt.manager.views.MainWindow.<init>(MainWindow.java:46)
        at org.openaudible.desktop.swt.manager.Application.createMainBody(Application.java:46)
        at org.openaudible.desktop.swt.manager.Application.createLayout(Application.java:55)
        at org.openaudible.desktop.swt.manager.Application.initComponents(Application.java:75)
        at org.openaudible.desktop.swt.gui.GUI.startUp(GUI.java:184)
        at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:113)
        at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:138)
        at org.openaudible.desktop.Application.main(Application.java:45)

**Comment by openaudible** [comment]
Thank you. Unexpected error. 

I’ll get an updated version posted tomorrow.

**Comment by Riccardo2017** [comment]
I just installed the version 3.5.4 and I can start OpenAudible without errors.

Thanks!

**Comment by openaudible** [comment]
Thanks for the report. Very unusual bug.. but the line of code that failed said something about it being hacking and making assumptions.. so not a huge surprise it failed there! But the error log really helped. 
Cheers.
