### ISSUE TITLE
Application won't open.

### ISSUE THREAD

**Issue by kilmerc** [openaudible/openaudible#988]
Nothing happens when trying to open the application. 

The log indicates no read/write access or something but I have been using this application for some time on this machine, not sure why it all of a sudden thinks I don't have access. 

Intel Mac OS 12.5
Library is stored on an external drive that is on and working properly.

Any ideas of what I can do to get back in business? Thanks in advance.

Log file says the following:
Jul 31, 2022 2:24:42 PM org.openaudible.desktop.swt.gui.GUI <init>
SEVERE: Error creating working directory
java.lang.NullPointerException
	at org.openaudible.Directories.cleanMetaDir(Directories.java:719)
	at org.openaudible.Directories.init(Directories.java:274)
	at org.openaudible.Directories.init(Directories.java:150)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:74)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:141)
	at org.openaudible.desktop.Application.main(Application.java:48)

Jul 31, 2022 2:24:42 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error creating directories!
Unable to create or load required directories. Check that the drives are read/writable. 
Error:null
You could also look at or erase the directories.json file.
Jul 31, 2022 2:24:42 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
java.lang.NullPointerException
	at org.openaudible.desktop.swt.gui.MessageBoxFactory$ThemedMessageDialog.createContents(MessageBoxFactory.java:187)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1081)
	at org.eclipse.jface.window.Window.open(Window.java:785)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory$3.task(MessageBoxFactory.java:234)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:292)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:183)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:147)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory.showGeneral(MessageBoxFactory.java:218)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory$1.task(MessageBoxFactory.java:103)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:292)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:183)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:147)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory.showError(MessageBoxFactory.java:91)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory.showError(MessageBoxFactory.java:86)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:86)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:141)
	at org.openaudible.desktop.Application.main(Application.java:48)
Jul 31, 2022 2:24:42 PM org.openaudible.desktop.swt.gui.GUI run
SEVERE: Error running GUI task showGeneral' [9514]
java.lang.NullPointerException
	at org.openaudible.desktop.swt.gui.MessageBoxFactory$ThemedMessageDialog.createContents(MessageBoxFactory.java:187)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1081)
	at org.eclipse.jface.window.Window.open(Window.java:785)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory$3.task(MessageBoxFactory.java:234)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:292)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:183)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:147)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory.showGeneral(MessageBoxFactory.java:218)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory$1.task(MessageBoxFactory.java:103)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:292)
	at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:183)
	at org.openaudible.desktop.swt.gui.SWTAsync.block(SWTAsync.java:147)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory.showError(MessageBoxFactory.java:91)
	at org.openaudible.desktop.swt.gui.MessageBoxFactory.showError(MessageBoxFactory.java:86)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:86)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:141)
	at org.openaudible.desktop.Application.main(Application.java:48)

**Comment by openaudible** [comment]
That is a bug. Not sure why you’re getting it though. Maybe the directory your library or preferences in is no longer available or writable? Or an anti-virus? Or out of disk space? The log is super helpful but unfortunately doesn’t have the full path of the directory having the problem. I’ll fix the error and write more details for the next beta and you check the above items. Will post soon.

**Comment by openaudible** [comment]
Fixed in the beta:
https://openaudible.org/beta
Let me know how it goes and if you see any errors in the console.
Appreciate the report!
