### ISSUE TITLE
Imported AXX file state says "No audio file or download link"

### ISSUE THREAD

**Issue by moritzWa** [openaudible/openaudible#991]
Hi, when I import an AXX file I can't convert it. 

<img width="782" alt="image" src="https://user-images.githubusercontent.com/42035131/182596548-1b94f9a7-8608-428f-9d7b-df38f2531a92.png">

I have an active license
<img width="574" alt="Screenshot 2022-08-03 at 13 25 54" src="https://user-images.githubusercontent.com/42035131/182596908-a0f90d7d-aad4-48eb-a56b-965f9e68af15.png">

I'm on 3.5.8 intel.
<img width="312" alt="image" src="https://user-images.githubusercontent.com/42035131/182597016-566528ab-ff39-4498-8187-40d254887ef5.png">

Please help.

**Comment by openaudible** [comment]
Go ahead and make a copy of the aax, right click that book and delete it. Then import the aax by dragging and dropping the aax file onto OpenAudible. Then attempt to convert it. Look at the File/ Console to spot any errors. 

Not all aax files can be converted, but the error message should be something other than what you got.

**Comment by moritzWa** [comment]
I'm getting this.

```
Aug 07, 2022 7:02:17 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.desktop.swt.manager.ImportExport _importFile
INFO: Copying file /Users/moritz/Downloads/audibooks axx/TheMythofArtificialIntelligenceWhyComputersCantThinktheWayWeDo_ep7 copy.aax to /Users/moritz/Library/OpenAudible/aax/TheMythofArtificialIntelligenceWhyComputersCantThinktheWayWeDo_ep7 copy.AAX
Aug 07, 2022 7:02:18 AM org.openaudible.desktop.swt.manager.ImportExport importFiles
SEVERE: import of /Users/moritz/Downloads/audibooks axx/TheMythofArtificialIntelligenceWhyComputersCantThinktheWayWeDo_ep7 copy.aax failed.
java.io.FileNotFoundException: /Users/moritz/Library/OpenAudible/aax/TheMythofArtificialIntelligenceWhyComputersCantThinktheWayWeDo_ep7 copy.AAX (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.openaudible.util.CopyWithProgress.copyWithProgress(CopyWithProgress.java:52)
	at org.openaudible.desktop.swt.manager.ImportExport._importFile(ImportExport.java:431)
	at org.openaudible.desktop.swt.manager.ImportExport.importFiles(ImportExport.java:136)
	at org.openaudible.desktop.swt.manager.ImportExport$1.run(ImportExport.java:1137)

Aug 07, 2022 7:02:18 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 1040 to disk:/Users/moritz/Library/OpenAudible/tmp/saved_books.json
Aug 07, 2022 7:02:18 AM org.openaudible.Audible save
INFO: Saved books took 20 ms. to complete.
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/art
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/art
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:18 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:21 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:21 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:21 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:21 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:21 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:21 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:28 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:28 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:28 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:28 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:28 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:28 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:31 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Aug 07, 2022 7:02:31 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:31 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:31 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:31 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:31 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
Aug 07, 2022 7:02:31 AM org.openaudible.Directories isValid
INFO: Not found:/Users/moritz/Library/OpenAudible/aax
```

**Comment by moritzWa** [comment]
looks like `openaudible.Directories isValid`

**Comment by moritzWa** [comment]
Also here's my diagnostics

```
{
 "date": "Sun Aug 07 07:05:40 CEST 2022",
 "books.json": "/Users/moritz/Library/OpenAudible/books.json",
 "memory": "Memory: Using 43.984Mb of 4096Mb (1%) Min 43.984Mb Max 43.984Mb",
 "directories": [
  {
   "path": "/Users/moritz/Library/OpenAudible",
   "kind": "BASE",
   "exists": true
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/books",
   "kind": "BOOKS",
   "exists": true
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/web",
   "kind": "WEB",
   "exists": false
  },
  {
   "path": "/Users/moritz/Library/OpenAudible",
   "kind": "META",
   "exists": true
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/aax",
   "kind": "AAX",
   "exists": false
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/art",
   "kind": "ART",
   "exists": false
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/books",
   "kind": "MP3",
   "count": 0,
   "exists": true,
   "sample": "/Users/moritz/Library/OpenAudible/books/sample.mp3"
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/tmp",
   "kind": "TMP",
   "exists": true
  },
  {
   "path": "/Applications/OpenAudible.app/Contents/Resources/app",
   "kind": "APP",
   "exists": true
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/books",
   "kind": "M4A",
   "count": 0,
   "exists": true,
   "sample": "/Users/moritz/Library/OpenAudible/books/sample.m4a"
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/books",
   "kind": "M4B",
   "count": 0,
   "exists": true,
   "sample": "/Users/moritz/Library/OpenAudible/books/sample.m4b"
  },
  {
   "path": "/Users/moritz/Library/OpenAudible/books",
   "kind": "PDF",
   "exists": true
  }
 ],
 "gui": {
  "swt_platform": "cocoa",
  "main_window": "Rectangle {19, 25, 790, 703}",
  "browser": {
   "prefer_chromium": false,
   "oa_chromium": "",
   "swtBrowserStyle": 0,
   "Desktop.isDesktopSupported": true,
   "externalBrowser": true,
   "Desktop.Action.BROWSE": true,
   "externalBrowserMode": "desktop",
   "oa_internal_browser": "",
   "browseWebCmd": ""
  },
  "display": {
   "highContrast": false,
   "bounds": "Rectangle {0, 0, 1680, 1050}",
   "dpi": "Point {72, 72}"
  },
  "aspect": 1.1237553,
  "theme": {
   "dark_debug": "set  org.eclipse.swt.display.useSystemTheme from  to true\n",
   "org.eclipse.swt.display.useSystemTheme": "true",
   "theme": "system",
   "is_dark": false
  },
  "swt_version": 4950
 },
 "compile_date": "2022-07-28 16:07",
 "region": "US",
 "version": "3.5.8",
 "demo": false,
 "platform": "mac",
 "properties": {
  "org.eclipse.swt.display.useSystemTheme": "true",
  "oa_external": "",
  "file.encoding": "UTF-8",
  "os": "ProductName:\tmacOS\nProductVersion:\t12.5\nBuildVersion:\t21G72\n",
  "java.version": "11.0.15",
  "oa_chromium": "",
  "sun.jnu.encoding": "UTF-8",
  "SWT_GTK3": "null",
  "OPENAUDIBLE_HOME": "",
  "locale": "LANG=\"en_DE.UTF-8\"\nLC_COLLATE=\"C\"\nLC_CTYPE=\"C\"\nLC_MESSAGES=\"C\"\nLC_MONETARY=\"C\"\nLC_NUMERIC=\"C\"\nLC_TIME=\"C\"\nLC_ALL=\n",
  "oa_internal_browser": "",
  "oa_packaging": ""
 },
 "prefs": {
  "disableVersionCheck": false,
  "lastVersion": "3.5.8",
  "playFileCmd": "",
  "webPageIncludeMP3": true,
  "format": "M4B",
  "autoConvert": true,
  "mp3Qscale": 4,
  "autoDownload": false,
  "language": "en",
  "autoWebPage": false,
  "autoRefreshMinutes": 0,
  "autoConnect": false,
  "uid": "1659525300166",
  "concurrentConversions": 3,
  "browseFileCmd": "",
  "autoLink": false,
  "concurrentDownloads": 3,
  "browser": "",
  "html": false,
  "theme": "",
  "autoPDF": true,
  "migrated": true,
  "region": "US",
  "browseWebCmd": ""
 }
}
```

**Comment by openaudible** [comment]
OK. I think that is fixed in the beta. Can you give it a try?
https://openaudible.org/beta

**Comment by moritzWa** [comment]
that works. Thanks!
